### ISSUE TITLE
A request for Fedora/RPM version

### ISSUE THREAD

**Issue by razzmatazz** [TablePlus/TablePlus-Linux#1]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
n/a

3. The steps to reproduce this issue:
Cannot install it on Fedora 31.

**Comment by chris-tse** [comment]
+1 For Fedora support. Or possibly a snap version for cross (Linux) platform?

**Comment by paulqwerty** [comment]
+1 for RPM version...  

Just tried the alpha build 24 on CentOS 8 and it looks great so far - Congratulations!

PS: mysql  Ver 15.1 Distrib 5.5.60-MariaDB, text and longtext cells show EMPTY and NULL if there is no data in them - I wish they would not have those values, I wish they would be just empty OR at least would be styled differently from the rest of cells that actually have some data filled in - maybe 40% opacity.

Additionally, when selecting the cell to enter data the EMPTY/NULL values should be removed, currently EMPTY/NULL values stay and it looks like the cell has the actual value of EMPTY or NULL...

Hope you don't mind my comments.

Thank you for your effort to bring this great software to the world!

Paul

**Comment by huyphams** [comment]
Hi @paulqwerty TablePlus Linux build is 36 now, and all those issues seem to be fixed.

**Comment by paulqwerty** [comment]
RPM version 36? Where can I get that?

I only saw DEB version (36) here: https://tableplus.com/blog/2019/10/tableplus-linux-installation.html

**Comment by huyphams** [comment]
Currently, TablePlus team only maintains the Debian repo https://tableplus.com/blog/2019/10/tableplus-linux-installation.html 
We will release other distros when it comes to beta. So you have to port it to RPM or wait for the beta.

**Comment by paulqwerty** [comment]
Ok, just ported the v36 to RPM, looks cool - thanks!

**Comment by bm-skutzke** [comment]
I tried to install https://deb.tableplus.com/rpm/x86_64/tableplus-0.1.24-2.x86_64.rpm on Fedora 31, but got an error:

`Problem: conflicting requests
    nothing provides libldap_r-2.4.so.2(OPENLDAP_2.4_2)(64bit) needed by tableplus-0.1.24-2.x86_64`

The currently installed `openldap-2.4.47-3.fc31.x86_64` package only provides
**libldap_r-2.4.so.2()(64bit)**
but not
**libldap_r-2.4.so.2(OPENLDAP_2.4_2)(64bit)**

Looks like a wrong dependency.

**Comment by huyphams** [comment]
Hi @bm-skutzke it's the test file, we only support Debian at the moment.

**Comment by trepatudo** [comment]
An AppImage should be really easy to build, I'm a paying customer for Mac which uses Linux quite often and I really think it's too long without any decent Linux update.

**Comment by wastrachan** [comment]
> An AppImage should be really easy to build, I'm a paying customer for Mac which uses Linux quite often and I really think it's too long without any decent Linux update.

They actually update this _alpha_ software almost every week, it's moving along fairly nicely, especially for a product they once said they'd never consider!

You may want to add your voice/vote for an AppImage on #17 -- that seems to be where the discussion around alternative packaging is centered.

**Comment by trepatudo** [comment]
> > An AppImage should be really easy to build, I'm a paying customer for Mac which uses Linux quite often and I really think it's too long without any decent Linux update.
> 
> They actually update this _alpha_ software almost every week, it's moving along fairly nicely, especially for a product they once said they'd never consider!
> 
> You may want to add your voice/vote for an AppImage on #17 -- that seems to be where the discussion around alternative packaging is centered.

Thanks for the info, was not aware of such.
I did run it via docker and it seemed ok for local development.

**Comment by dkgndianko** [comment]
Successfully installed on **Fedora Workstation 32** with this steps:
1. Download the **Debian** package from official sources [there](https://deb.tableplus.com/debian/pool/main/t/tableplus/tableplus_0.1.64_amd64.deb)
1. Installing some dependencies:
```bash
sudo dnf install openldap openldap-devel libgee libgee-devel gtksourceview-devel gtksourceview2-devel gtksourceview3-devel gtksourceview4-devel libgnome-keyring-devel gnome-keyring gnome-keyring-pam
```
1. Transform from `.deb` to `.rpm` using **alien**:
```bash
sudo alien --to-rpm --scripts tableplus_0.1.64_amd64.deb
```
1. Edit the newly created `.rpm` package to remove un-necessary dependency and conflicting directory using **rpmrebuild**
```bash
rpmrebuild -pe tableplus-0.1.64-2.x86_64.rpm
```
In edition you can delete or comment the line with wrong dependency (Here it is `Requires:      libldap_r-2.4.so.2(OPENLDAP_2.4_2)(64bit)`)
Also under `%files` remove the line containing this: `%dir %attr(0755, root, root) "/"`.
Save and get the path where the new package is saved.
1. You can install and enjoy it.
In my case it is:
```bash
sudo dnf install /home/dkgndianko/rpmbuild/RPMS/x86_64/tableplus-0.1.64-2.x86_64.rpm
```

**Comment by cognitus** [comment]
In that case isn't better provide a .tar.gz like other services such as discord, anydesk, etc. or an AppImage

**Comment by Melvasul** [comment]
@dkgndianko the link for the Debian package is no longer active |:

**Comment by glendmaatita** [comment]
hi @Melvasul , try [this link](https://deb.tableplus.com/debian/pool/main/t/tableplus/tableplus_0.1.74_amd64.deb)

**Comment by dkgndianko** [comment]
@Melvasul I updated the comment. Thank you for pointing out.
Thank you @glendmaatita for the new link.

**Comment by Melvasul** [comment]
@dkgndianko everything worked as intended
but is it me, or is TablePlus basically empty?
Everything is on "coming" and I can't export/import any table at all...
![Screenshot from 2021-02-18 00-11-00](https://user-images.githubusercontent.com/11297488/108280018-cf6fe680-717d-11eb-9f40-37da3dd2e299.png)

**Comment by dkgndianko** [comment]
> @dkgndianko everything worked as intended
> but is it me, or is TablePlus basically empty?
> Everything is on "coming" and I can't export/import any table at all...
> ![Screenshot from 2021-02-18 00-11-00](https://user-images.githubusercontent.com/11297488/108280018-cf6fe680-717d-11eb-9f40-37da3dd2e299.png)

Sorry @Melvasul, bu I'm not familiar with @TablePlus roadmap. Maybe you should raise an issue for that.

**Comment by tylucaskelley** [comment]
Would be cool to get an update from the TablePlus devs on the place this has on the roadmap - loved using this tool on macOS and would be great to come back to it on Fedora.

**Comment by dkgndianko** [comment]
> Would be cool to get an update from the TablePlus devs on the place this has on the roadmap - loved using this tool on macOS and would be great to come back to it on Fedora.

You are absolutely right.
What do we need to do to make that happen?

**Comment by frafra** [comment]
`gtksourceview-devel` seems missing on Fedora 34.

```
$ sudo alien --to-rpm --scripts tableplus_0.1.176_amd64.deb 
tableplus-0.1.176-2.x86_64.rpm generated
$ sudo dnf install tableplus-0.1.176-2.x86_64.rpm
Error: 
 Problem: conflicting requests
  - nothing provides libc.so.6(GLIBC_PRIVATE)(64bit) needed by tableplus-0.1.176-2.x86_64
  - nothing provides libldap_r-2.4.so.2(OPENLDAP_2.4_2)(64bit) needed by tableplus-0.1.176-2.x86_64
$ sudo rpm -Uhv --nodeps tableplus-0.1.176-2.x86_64.rpm
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
	file /opt from install of tableplus-0.1.176-2.x86_64 conflicts with file from package filesystem-3.14-5.fc34.x86_64
```

**Comment by javis** [comment]
+1 for RPM or Flatpack or even AppImage plz!

**Comment by ebdavison** [comment]
+1 for RPM and/or Flatpack

**Comment by xcy7e** [comment]
+1 for RPM and/or Flatpack

**Comment by tkhquang** [comment]
+1 for RPM and/or Flatpack

**Comment by gcg** [comment]
+1 for flatpak :)

**Comment by KeivanDjafarizad** [comment]
+1 for RPM and/or Flatpak

**Comment by tylucaskelley** [comment]
Do the table plus maintainers still check this repo? Would love to see this on Fedora without having to hack around using the .deb file.

**Comment by benounnas** [comment]
come on ! at least a flatpack or snap, it's like a discrimination :disappointed:

**Comment by guiazv** [comment]
Flatpak support would be great! :)

**Comment by pareshpandit** [comment]
+1 for RPM/Flatpak pkgs ... :)  _/|\_

**Comment by pareshpandit** [comment]
> 

This is indeed a super idea, and I tried it will all my might, but just could not get those requirements (dependencies) to vanish. 

In the end, if I edited the .rpm with |sudo rpmrebuild|, still, all I could get success-with, was the installation. But post the installation, the error again showed-up as under: 

```tableplus: error while loading shared libraries: libsasl2.so.2: cannot open shared object file: No such file or directory```

I do not know how to go about it, for now. Any tips? _/|\_

Also: could anyone actually share their (working) recompiled .RPM ? :)

**Comment by CaelumF** [comment]
DataGrip installs easily on Fedora using the toolbox, and JetBrain's model of Linux-friendliness would be very well suited for TablePlus

**Comment by omarvaldez5** [comment]
+1 for RPM or Flatpak!!!!!!

**Comment by jdeathe** [comment]
+1 for RPM

**Comment by Michael-Vol** [comment]
+1 for RPM/Flatpak

**Comment by psydvl** [comment]
Can I subscribe for something like waitlist for rpm or flatpak?
NB: I'm using openSUSE, so fedora's rpm maybe a little incompatible, because some libraries have different naming

**Comment by darkufo** [comment]
Would love this for Fedora.

**Comment by muhammadshaban** [comment]
+1 for RPM/Flatpak

**Comment by BranchScope** [comment]
+1 bruh, really need it

**Comment by threeaccents** [comment]
I wouldn't get my hopes up. I don't think this is coming any time soon.

**Comment by joega** [comment]
> I wouldn't get my hopes up. I don't think this is coming any time soon.

https://twitter.com/TablePlus/status/1634785633486139393   👀

**Comment by huyphams** [comment]
Actually, I can run it on Centos Stream 9 right now.
![CleanShot 2023-03-29 at 13 18 07@2x](https://user-images.githubusercontent.com/3654622/228443480-a5f8fe66-2001-4c4b-a87c-8b0013bafb13.png)

**Comment by huyphams** [comment]
And Fedora 36 ARM version.
<img width="1728" alt="Screenshot 2023-03-30 at 1 14 05 AM" src="https://user-images.githubusercontent.com/3654622/228630481-d682f023-0c41-423b-8d98-d3df72929cc2.png">

**Comment by huyphams** [comment]
Next step:

- Create a yum/dnf repo for distribution.

**Comment by darkufo** [comment]
@huyphams  How to best install on Fedora 37.

**Comment by huyphams** [comment]
@darkufo let me try to create a test repo tomorrow and see how it goes. I'm gonna offline now (it's midnight here). Good night.

**Comment by darkufo** [comment]
@huyphams  Perfect, no rush :) Sleep well

**Comment by huyphams** [comment]
Please check it out!
https://tableplus.com/linux/install
