### ISSUE TITLE
Package not installable on Ubuntu 18.04 - libnm-dev

### ISSUE THREAD

**Issue by brysonreece** [TablePlus/TablePlus-Linux#10]
Ubuntu 18.04 on `apt install tableplus`:

```bash
The following packages have unmet dependencies:
    tableplus : Depends: libnm-dev but it is not going to be installed
```

It seems `libnm-dev` has its own requirement issues when investigating further:

```bash
The following packages have unmet dependencies:
    libnm-dev : Depends: libnm0 (= 1.10.6-2ubuntu1.2) but 1.10.14-0ubuntu2 is to be installed
                Depends: gir1.2-nm-1.0 (= 1.10.6-2ubuntu1.2) but 1.10.14-0ubuntu2 is to be installed
```

Unfortunately downgrading those two packages is impossible (well, inconvenient) as it removes `ubuntu-desktop` and a number of `gnome-network` tools as dependents.

**Comment by huyphams** [comment]
Hey @brysonreece could you please try to run

```
sudo apt update && sudo apt install tableplus 
```

again? I just statically link the libnm, TablePlus now will not require the libnm anymore.

**Comment by brysonreece** [comment]
Heck yeah, it worked! Way to go!

**Comment by cedricxie** [comment]
Hi @huyphams , I am trying to install on Ubuntu 14. But looks like `libnm` is not statically linked. Is this the case? Thank you.

**Comment by huyphams** [comment]
Yep, it's not. I'm trying to do it.

**Comment by cedricxie** [comment]
Awesome. Thanks!

**Comment by huyphams** [comment]
Hey @cedricxie , please try to install/update the app, libnm is no longer required in build 22.

**Comment by cedricxie** [comment]
Hi @huyphams , thanks for the help! Now I get a different error though.
```tableplus: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by tableplus)
tableplus: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by tableplus)
```

**Comment by brysonreece** [comment]
@huyphams should these be filed as different issues?
