### ISSUE TITLE
Unable to install in ubuntu 20.04

### ISSUE THREAD

**Issue by shankhadevpadam** [TablePlus/TablePlus-Linux#100]
```
Err:9 https://deb.tableplus.com/debian tableplus InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 2A17818B38772786
Reading package lists... Done
W: GPG error: https://deb.tableplus.com/debian tableplus InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 2A17818B38772786
E: The repository 'https://deb.tableplus.com/debian tableplus InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

```

**Comment by mkhuramj** [comment]
Hi,
I also getting the following error when I try to install tableplus on my Ubuntu 20.04. Here are the error details:


`      

    sudo apt install tableplus
	Reading package lists... Done
	Building dependency tree       
	Reading state information... Done
	Some packages could not be installed. This may mean that you have
	requested an impossible situation or if you are using the unstable
	distribution that some required packages have not yet been created
	or been moved out of Incoming.
	The following information may help to resolve the situation:

	The following packages have unmet dependencies:
	 tableplus : Depends: libgtksourceview-3.0-dev but it is not going to be installed
	E: Unable to correct problems, you have held broken packages.`

**Comment by dnlsgv** [comment]
In ubuntu 20.04 these steps worked well for me:

```bash
# Add TablePlus gpg key
wget -O - -q http://deb.tableplus.com/apt.tableplus.com.gpg.key | sudo apt-key add - 

# Add TablePlus repo
sudo add-apt-repository "deb [arch=amd64] https://deb.tableplus.com/debian tableplus main"

# Install
sudo apt update
sudo apt install tableplus
```

**Comment by shankhadevpadam** [comment]
@dnlsgv it's not working for me.

**Comment by rajanmandanka** [comment]
lenovo@lenovo:~$ wget -O - -q http://deb.tableplus.com/apt.tableplus.com.gpg.key | sudo apt-key add -
OK
lenovo@lenovo:~$ sudo add-apt-repository "deb [arch=amd64] https://deb.tableplus.com/debian tableplus main"

Hit:1 http://in.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 https://deb.tableplus.com/debian tableplus InRelease                  
Get:3 http://security.ubuntu.com/ubuntu focal-security InRelease [109 kB]   
Fetched 109 kB in 1s (82.6 kB/s)   
Reading package lists... Done
lenovo@lenovo:~$ 
lenovo@lenovo:~$ sudo apt update
Hit:1 http://in.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 https://deb.tableplus.com/debian tableplus InRelease                 
Hit:3 http://security.ubuntu.com/ubuntu focal-security InRelease
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
lenovo@lenovo:~$ sudo apt install tableplus
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 tableplus : Depends: libgtksourceview-3.0-dev but it is not going to be installed
             Depends: libgee-0.8-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by ajinkya14-zoomcar** [comment]
### same issue ###

sudo apt install tableplus
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 tableplus : Depends: libgtksourceview-3.0-dev but it is not going to be installed
             Depends: libgee-0.8-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by Briandosha** [comment]
Getting the following issue any solutions?


The following packages have unmet dependencies:
 tableplus : Depends: libgtksourceview-3.0-dev but it is not going to be installed
             Depends: libgee-0.8-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by crydotsnake** [comment]
I get this error with Ubuntu 22.04

**Comment by FlavioScimeca** [comment]
same

**Comment by crydotsnake** [comment]
> In ubuntu 20.04 these steps worked well for me:
> 
> ```shell
> # Add TablePlus gpg key
> wget -O - -q http://deb.tableplus.com/apt.tableplus.com.gpg.key | sudo apt-key add - 
> 
> # Add TablePlus repo
> sudo add-apt-repository "deb [arch=amd64] https://deb.tableplus.com/debian tableplus main"
> 
> # Install
> sudo apt update
> sudo apt install tableplus
> ```

Fixed it for me. But i would prefer a `.deb` package.
