### ISSUE TITLE
0 rows affected on delete statement

### ISSUE THREAD

**Issue by eaguad1337** [TablePlus/TablePlus-Linux#103]
1. Database version: MySQL 5.7

2. TablePlus version: Version 0.1 (74)

3. Linux distro: Ubuntu 20.04

4. The steps to reproduce this issue:

- Open new SQL query Window.
- Execute a delete statement like: "delete from table".
- Rows affected will be zero.

**Comment by huyphams** [comment]
We've fixed this issue, it will be included in the next update! thanks!
