### ISSUE TITLE
[feature request] auto complete

### ISSUE THREAD

**Issue by elgs** [TablePlus/TablePlus-Linux#104]
Can you please prioritize auto complete? This will be a game changer. Thank you.

**Comment by huyphams** [comment]
We added this feature in build 82, it has not been supported context-awareness yet, but we're improving!
Thanks

**Comment by elgs** [comment]
Thank you! I found on Mac version, if I have a table called `some_table`, the auto complete works if I type st, but it doesn't work on the Linux version so far.
