### ISSUE TITLE
[BUG] app crashes when place cursor at the beginning of the first line in SQL query tab

### ISSUE THREAD

**Issue by konohorov** [TablePlus/TablePlus-Linux#106]
1. Database version (Ex: PostgreSQL 10.0): PostgreSQL 12.5

2. TablePlus version (the number on the welcome or about screen, Ex: build 81): Version 0.1 (78)

3. Linux distro (Ex: Ubuntu 18.04): Ubuntu 20.10

4. The steps to reproduce this issue:

- 1.  connect to DB
- 2.  open the New SQL query tab
- 3.  enter anything, e.g. 'SELECT'
- 4.  place the cursor at the beginning of the line (before the word ''SELECT) by clicking the mouse left button, press the 'Home' button on the keyboard, press the 'Left' button on the keyboard, etc.

![Screenshot_20210323170505](https://user-images.githubusercontent.com/50928047/112168478-02cce780-8bfa-11eb-9ce7-008b79bb5ba6.png)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by jamosaur** [comment]
Also experiencing this on Linux Mint 20, MySQL 8.0.23

**Comment by huyphams** [comment]
Hi @jamosaur @konohorov please upgrade the app to build 80, it should fix the issue. Thanks!

**Comment by jamosaur** [comment]
thanks @huyphams, can confirm it's fixed now
