### ISSUE TITLE
Empty table are not shwoing up

### ISSUE THREAD

**Issue by amirping** [TablePlus/TablePlus-Linux#109]
1. Database version (Ex: PostgreSQL 10.0):
postgresql 11.11
2. TablePlus version (the number on the welcome or about screen, Ex: build 81):
80
3. Linux distro (Ex: Ubuntu 18.04): 
Debian buster
4. The steps to reproduce this issue:
just connect to db

**Comment by huyphams** [comment]
I don't understand the issue, could you explain it or attach a screenshot please

**Comment by huyphams** [comment]
Please try to change the db or schema at the bottom. Thanks.

**Comment by amirping** [comment]
Schema is changed, but empty tables are not visible.
![image](https://user-images.githubusercontent.com/3626339/115545406-ae219880-a29b-11eb-8dfb-07ad5962d8fd.png)

**Comment by huyphams** [comment]
Did you put the database name into the connection form?

**Comment by amirping** [comment]
yeap sure

**Comment by huyphams** [comment]
Within the title bar on the screenshot, I can only see the connection name, I believe that you forgot to enter the database name. Please double check it.
