### ISSUE TITLE
Empty ≠ NULL

### ISSUE THREAD

**Issue by Kogurex** [TablePlus/TablePlus-Linux#110]
1. Database version (5.7.33-0ubuntu0.18.04.1):

2. TablePlus version (Alpha Build 80):

3. Linux distro (Linux x64-HPLaptop 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux): 

4. The steps to reproduce this issue: Connect and open any table. When reviewing with another client, it is shown by NULL but in SQLPlus that says 'Empty'.

Attached comparison with Navicat... I have to mention that in adminer, those values are NULL too...
![Captura de pantalla_2021-04-20_10-30-32](https://user-images.githubusercontent.com/11504405/115413843-87902e80-a1c3-11eb-85f9-1553c963b462.png)

**Comment by huyphams** [comment]
It's fixed in the release 94, thanks!
