### ISSUE TITLE
Mongodb Connection

### ISSUE THREAD

**Issue by Deathsooul** [TablePlus/TablePlus-Linux#111]
Hey guys, how u doing?
Why Table plus didn't support MongoDB connection for Linux users ?
It'll be wonderful 

 Linux distro: Ubuntu 20.04

**Comment by polarizeme** [comment]
I know it's annoying to get "me too" comments on issues, but if you're not going to include MongoDB connections in this alpha, please at least state that on the download page so that folks aren't downloading it only to discover there's no MongoDB connection support on Linux yet ;] ;[

**Comment by huyphams** [comment]
In the linux page, there is no mongo or oracle. The mongo is only on the macos page

**Comment by Deathsooul** [comment]
> In the linux page, there is no mongo or oracle. The mongo is only on the macos page

yeah, but if it exist for macos why not implement for linux too?
it'll be useful

**Comment by huyphams** [comment]
It's added in the release 108. Thanks
