### ISSUE TITLE
Host name localhost translated to /var/run/mysqld/mysqld.sock

### ISSUE THREAD

**Issue by Shikachuu** [TablePlus/TablePlus-Linux#114]
1. Database version (Ex: PostgreSQL 10.0): MariaDB 10.5.8, MySQL 8.0

2. TablePlus version (the number on the welcome or about screen, Ex: build 81): 0.1 (84)

3. Linux distro (Ex: Ubuntu 18.04):  PopOS 20.10

4. The steps to reproduce this issue:
Create a new connection to localhost.
![Screenshot from 2021-04-30 12-31-30](https://user-images.githubusercontent.com/32636587/116683789-9cc54400-a99f-11eb-8752-599bfeae7385.png)

I run MariaDB in a docker container with port 3306 forwarded to host. When I wanted to create a new connection to localhost, the above image show what happened. Same thing happens using MySQL.

_As a workaround I change the host to 127.0.0.1 and it is working perfectly fine._

**Comment by huyphams** [comment]
Hi, it was translated automatically by the driver (not TablePlus), because the localhost was not accepted so it fallback to socket, i believe. so there is nothing we can do about it.
