### ISSUE TITLE
Add a shortcut to open a new window (similar to new workspace)

### ISSUE THREAD

**Issue by wout** [TablePlus/TablePlus-Linux#118]
1. Database version (Ex: PostgreSQL 10.0):
N/A

2. TablePlus version (the number on the welcome or about screen, Ex: build 81):
Build 84

3. Linux distro (Ex: Ubuntu 18.04): 
elementary OS 6

4. The steps to reproduce this issue:
I prefer to work with new windows rather than new workspaces, so I would love a shortcut for new windows as well. I think `ctrl` + `shift` + `n` would be great as it's not used for anything else.

**Comment by huyphams** [comment]
Added, it will be released in the next update!

**Comment by wout** [comment]
@huyphams You're the best. This app is really great! :)

**Comment by huyphams** [comment]
The build 98 includes this shortcut, along with some new UI enhancements, bug fixes and new features.
