### ISSUE TITLE
SSH tunnel fails to connect

### ISSUE THREAD

**Issue by brysonreece** [TablePlus/TablePlus-Linux#12]
On `Ubuntu 18.04`, creating an SSH tunnel to "local" database on remote machine fails to connect.

A functional workaround is to run in a separate window:
```bash
ssh USER@HOST -L 3306:127.0.0.1:3306 -N
```

After that, setting up the database works correctly once pointed to local `127.0.0.1` and configured to not utilize an SSH tunnel.

**Comment by huyphams** [comment]
Could you post the error message please @brysonreece thank you

**Comment by brysonreece** [comment]
The error I'm receiving:

<img src="https://user-images.githubusercontent.com/4043157/70107001-ebd04380-160a-11ea-817a-3eea0d61e07f.png" width="360" />


Failing input data:

<img src="https://user-images.githubusercontent.com/4043157/70107034-00144080-160b-11ea-9e39-64ec51b8c81e.png" width="480" />

After running the above command, this input data allows me to interact with my database like normal:

<img src="https://user-images.githubusercontent.com/4043157/70107100-36ea5680-160b-11ea-9ba8-62ceeee03877.png" width="480" />

**Comment by huyphams** [comment]
I've checked the SSH code and there is only one place that would report the error `Failed to connect!`:
TablePlus could not ping the ssh host. Could you please try again with the IP address instead of the domain name?

**Comment by brysonreece** [comment]
That works! Is there a plan to support FQDNs any time soon?

**Comment by wastrachan** [comment]
I've reproduced this issue in Arch Linux-- and I can confirm using the IP address instead of the hostname does seem to work. 

In addition to hostname resolution (apparently) not working, it looks like any local SSH configuration for a host is ignored (e.g.-- I MUST supply an SSH key in the TablePlus configuration, even if my SSH configuration has one specific). This seems (if memory serves) contrary to the behavior of the MacOS version.

**Comment by brysonreece** [comment]
A potential method of determining SSH configuration could be to query the local SSH agent (if one exists) and only prompt for connection info if the requested host config is not found.

**Comment by huyphams** [comment]
This is an alpha release and still missing may features. The official (or upcoming builds) will support:
- Support the SSH config file.
- Support domain name.
- Support socket forwarding (not only port).

**Comment by brysonreece** [comment]
Awesome, glad to hear it! Thanks for the help Henry!

**Comment by huyphams** [comment]
Hey @brysonreece TablePlus build 18 now support:
- Respect SSH Config.
- Domain and IP addresses are supported.

Please update to the latest release, thank you!

**Comment by huyphams** [comment]
The SSH is also much faster than the previous version.

**Comment by hummal** [comment]
Just FYI: In our company we prevent some servers to get pinged. As I understand you only connect ssh tunnels if you can ping the server. This won't work with our setup. Please at least insert any options to choose to use ping or not. Need to go back to SequelPro

**Comment by huyphams** [comment]
Hi @hummal are you using SequelPro in Linux? also Sequel Pro is using open SSH to make a tunnel while TablePlus implement it owns using libssh (a RedHat open source), they are very similar (in term of how it works). Open SSH supports more option tha libssh because it is much older.

**Comment by hummal** [comment]
Iam working on OSX Catalina. It is really sad I cant use TablePlus with SSH Tunnels

**Comment by huyphams** [comment]
But this was the Linux Repo (the macOS repo here: https://github.com/TablePlus/TablePlus). If you're using the macOS version you can turn on the debug and see what's going on.

<img width="1146" alt="Screen Shot 2020-04-08 at 11 19 26 PM" src="https://user-images.githubusercontent.com/3654622/78808281-65c86d00-79ef-11ea-83d6-88e9e67b762f.png">
