### ISSUE TITLE
Error adding gpg key on Ubuntu 21.04

### ISSUE THREAD

**Issue by kai3x5** [TablePlus/TablePlus-Linux#123]
1. Database version (Ex: PostgreSQL 10.0):

2. TablePlus version (the number on the welcome or about screen, Ex: build 81):

3. Linux distro (Ex: Ubuntu 18.04): 
Ubuntu 21.04

4. The steps to reproduce this issue:

PROBLEM:
Per the installation guide on website, it states:

`wget -O - -q http://deb.tableplus.com/apt.tableplus.com.gpg.key | sudo apt-key add - `

However, this gives the error:
`Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).`

SOLUTION:

Per debian docs, use the following command instead:
`wget -O- -q https://deb.tableplus.com/apt.tableplus.com.gpg.key | sudo tee /usr/share/keyrings/tableplus-archive-keyring.gpg`

**Comment by huyphams** [comment]
Thanks, We've updated the docs.
