### ISSUE TITLE
Great improvements in build 94, but auto complete still doesn't match macOS version's behavior.

### ISSUE THREAD

**Issue by elgs** [TablePlus/TablePlus-Linux#124]
1. Database version (Ex: PostgreSQL 10.0):
MariaDB 10.5.11

2. TablePlus version (the number on the welcome or about screen, Ex: build 81):
Alpha Build 94

3. Linux distro (Ex: Ubuntu 18.04): 
Arch Linux 5.13.10-arch1-1

4. The steps to reproduce this issue:

Thank you for build 94. Great improvement in auto completely.It's nearly usable now.

One thing that still doesn't match the TablePlus macOS version is for example I have a table `WORK_ORDER`, in macOS version, I could type `woor` and it will match the `WORK_ORDER`, but in Linux build 94, it doesn't match the order until the underscore is typed. Imagine I have 100 of tables like:
```
ONE_HUNDRED_TABLES_WITH_REALLY_LONG_NAMES_000
ONE_HUNDRED_TABLES_WITH_REALLY_LONG_NAMES_002
...
ONE_HUNDRED_TABLES_WITH_REALLY_LONG_NAMES_099
```

Current auto complete behavior is not really helpful to match any of the 100 tables.

**Comment by huyphams** [comment]
We are aware of it @elgs we are using fuzzy matching for macOS, Windows, iOS but not for Linux. We will bring it to Linux version next time.
Thanks

**Comment by huyphams** [comment]
The build 102 should support this feature now.
Thanks

**Comment by elgs** [comment]
Thank you so much! This is in my opinion making the Linux version significantly usable now.

**Comment by huyphams** [comment]
We just released the build 114. The previous build has the wrong score order. The fuzzy matching now work much better.
