### ISSUE TITLE
Auto complete does not include column names

### ISSUE THREAD

**Issue by elgs** [TablePlus/TablePlus-Linux#128]
### Please anwser the questions below, it helps us to track the issue.

1. Database version (Ex: PostgreSQL 10.0):
MariaDB 10.5.11

2. TablePlus version (the number on the welcome or about screen, Ex: build 81):
0.1(126) - Alpha release

3. Linux distro (Ex: Ubuntu 18.04): 
Linux arch 5.13.12-arch1-1 <span>#</span>1 SMP PREEMPT Wed, 18 Aug 2021 20:49:03 +0000 x86_64 GNU/Linux

4. The steps to reproduce this issue:
Auto complete seems to only include table names and SQL key words. Context aware column names do not seems to appear in the auto complete.

**Comment by mikej96** [comment]
I am experiencing this as well. table plus version .0 (214). 

I cannot get the column names to complete.

**Comment by elgs** [comment]
I moved on to DBeaver. DBeaver is much much better than it was 2 years ago. TablePlus is good, but autocomplete is essential for a tool like this. If autocomplete doesn't work properly, it's basically not usable.

**Comment by dsentker** [comment]
I moved to DataGrip yesterday. I paid for tableplus, but the most basic feature is not working properly. Absolutely disappointing.

**Comment by huyphams** [comment]
Hi @dsentker please contact the team to get refund. It is said that on the installing page that the app is still missing feature. It is also free to use.

**Comment by huyphams** [comment]
The autocompletion column will be added in the next update (within this week).
Thanks.
