### ISSUE TITLE
SQLite "This driver does not supported"

### ISSUE THREAD

**Issue by AnnoyingTechnology** [TablePlus/TablePlus-Linux#13]
![Screenshot from 2019-12-05 09-36-34](https://user-images.githubusercontent.com/5336824/70218184-d3634480-1742-11ea-9b73-000dafeb7a5a.png)

1. Database version (Ex: PostgreSQL 10.0):
SQLite 3

2. TablePlus version (the number on the welcome or about screen, Ex: build 81):
0.1-18amd64

3. Linux distro (Ex: Ubuntu 18.04): 
Debian 10.2

4. The steps to reproduce this issue:
exactly specified in https://tableplus.com/blog/2019/10/tableplus-linux-installation.html
+ opening any SQLite database

![Screenshot from 2019-12-05 09-36-42](https://user-images.githubusercontent.com/5336824/70218182-d2caae00-1742-11ea-8480-0b1f636d5e0f.png)

**Comment by AnnoyingTechnology** [comment]
I admit that SQlite, on Linux, might at the bottom of your priority list in terms of marketshare ;)

**Comment by huyphams** [comment]
Resolved in build 20 @AnnoyingTechnology thank you!
