### ISSUE TITLE
Could not open the app on Ubuntu 20.10

### ISSUE THREAD

**Issue by ashokbaruaakas** [TablePlus/TablePlus-Linux#131]
1. Database version (Ex: PostgreSQL 10.0): MySQL 8.0.26

2. TablePlus version (the number on the welcome or about screen, Ex: build 81): 0.1.176

3. Linux distro (Ex: Ubuntu 18.04): Ubuntu 21.10

4. The steps to reproduce this issue: Install and launch

**Comment by albin-joseph-101** [comment]
any solution ? 
getting the same error.

tableplus: error while loading shared libraries: libldap_r-2.4.so.2: cannot open shared object file: No such file or directory

@huyphams @brysonreece

**Comment by marknuyens** [comment]
Same problem here

**Comment by brysonreece** [comment]
@albin-joseph-101 Please do not tag project contributors in your bug reports. I am not the project maintainer. This issue itself generates a notification for the person who does happen to be the project maintainer, @huyphams, so tagging them is also redundant.

**Comment by Akkadius** [comment]
Linux user here, paid licenses, love your work

After Pop OS update getting

```
tableplus: error while loading shared libraries: libldap_r-2.4.so.2: cannot open shared object file: No such file or directory
```

Any advice? @huyphams

**Comment by huyphams** [comment]
I'm fixing this issue, a new update will be released within a few hours.

**Comment by huyphams** [comment]
<img width="1322" alt="Screen Shot 2021-12-23 at 10 20 37 PM" src="https://user-images.githubusercontent.com/3654622/147260173-f5d98f89-bbaf-4ac1-91b3-635e26e40fa3.png">

**Comment by Akkadius** [comment]
Thank you!!!!!!

**Comment by huyphams** [comment]
the installation page has been updated, please give it a try and let me know if you are still seeing the issue: 

https://tableplus.com/blog/2019/10/tableplus-linux-installation.html

If you've added the repo before, you might want to edit it to the new URL.

**Comment by Akkadius** [comment]
Hmm I still get the error even after pointing to the new repository URL

**Comment by Akkadius** [comment]
Nevermind. The installation page was cached and had to dump the cached page to get the new Ubuntu blocks

**Comment by programatorseu** [comment]
Hello Sir,
Amazing job - I have tried on OSX and it works like a charm.
I was trying to put on my main machine (pop os ) - and the same error with libldap

**Comment by hamidafghan** [comment]
To have a quick fix

Download and install the libldap-2.4-2 package in Ubuntu 20.19

https://packages.debian.org/buster/amd64/libldap-2.4-2/download

To install the downloaded package

sudo apt install ./PACKAGE_NAME

It fix the issue. 
![image](https://user-images.githubusercontent.com/21290137/153565258-4ca51b22-4af1-4b2f-bd55-93591ff1e883.png)

**Comment by maxwell8888** [comment]
I'm still having the same problem: `tableplus: error while loading shared libraries: libldap-2.5.so.0: cannot open shared object file: No such file or directory`

**Comment by thallysrc** [comment]
same here, on arch linux

**Comment by talbergs** [comment]
Same issue.

**Comment by SoulNinja-dev** [comment]
same issue

**Comment by DevP7** [comment]
Same issue with linux mint

**Comment by kt6delta** [comment]
same with linux mint

**Comment by gjrdiesel** [comment]
Like @hamidafghan had mentioned, for debian based OS, you can do the following:
```
wget http://http.us.debian.org/debian/pool/main/o/openldap/libldap-2.4-2_2.4.47+dfsg-3+deb10u7_amd64.deb

sudo apt install ./libldap-2.4-2_2.4.47+dfsg-3+deb10u7_amd64.deb
```

Just worked for me on `Ubuntu 22.04.1`

**Comment by black-code1** [comment]
> Like @hamidafghan had mentioned, for debian based OS, you can do the following:
> 
> ```
> wget http://http.us.debian.org/debian/pool/main/o/openldap/libldap-2.4-2_2.4.47+dfsg-3+deb10u7_amd64.deb
> 
> sudo apt install ./libldap-2.4-2_2.4.47+dfsg-3+deb10u7_amd64.deb
> ```
> 
> Just worked for me on `Ubuntu 22.04.1`

this command makes the app flashes, when i run tablesplus it opens and closed 2sec after

**Comment by programatorseu** [comment]
Ubuntu 22.10 has got libldap 2.5.13 and works perfecty. Tested tonight and brand new installation . Following manual from the web and works like a charm
