### ISSUE TITLE
TablePlus doesn't launch on Ubuntu 21.10

### ISSUE THREAD

**Issue by thesbx** [TablePlus/TablePlus-Linux#134]
### Please answer the questions below, it helps us to track the issue.

1. Database version: N/A 

2. TablePlus version: Build 154

3. Linux distro:  Ubuntu 21.10

4. The steps to reproduce this issue: Launch TablePlus from shortcut or command line fails

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by fabioxgn** [comment]
Might be the same issue as https://github.com/TablePlus/TablePlus-Linux/issues/133

**Comment by teekaytech** [comment]
I'm also having this error on ubuntu 21.10
GNOME version 40.4.0
Is there any update on this?

**Comment by RedBoool** [comment]
Same problem here, on Ubuntu 21.10 with Gnome.
Using XOrg and not Wayland, because it was fixing the problem on Ubuntu 21.04

Error message:
`tableplus: error while loading shared libraries: libldap_r-2.4.so.2: cannot open shared object file: No such file or directory`

**Comment by saagoor** [comment]
Having exact same issue.

`tableplus: error while loading shared libraries: libldap_r-2.4.so.2: cannot open shared object file: No such file or directory`

**Comment by lipemecprec** [comment]
I was having the same issue of 
`tableplus: error while loading shared libraries: libldap_r-2.4.so.2: cannot open shared object file: No such file or directory`
and I managed to **solve** it by installing libldap manually from: https://ubuntu.pkgs.org/18.04/ubuntu-main-amd64/libldap-2.4-2_2.4.45+dfsg-1ubuntu1_amd64.deb.html

```
wget http://archive.ubuntu.com/ubuntu/pool/main/o/openldap/libldap-2.4-2_2.4.45+dfsg-1ubuntu1_amd64.deb
sudo dpkg -i libldap-2.4-2_2.4.45+dfsg-1ubuntu1_amd64.deb
```

**Comment by teekaytech** [comment]
Thanks @lipemecprec 

I tried the method above and I got the following message:

```
Package libldap-2.4-2 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libldap-common

E: Package 'libldap-2.4-2' has no installation candidate
```

**Comment by thesbx** [comment]
> I was having the same issue of `tableplus: error while loading shared libraries: libldap_r-2.4.so.2: cannot open shared object file: No such file or directory` and I managed to **solve** it by installing libldap manually from: https://ubuntu.pkgs.org/18.04/ubuntu-main-amd64/libldap-2.4-2_2.4.45+dfsg-1ubuntu1_amd64.deb.html
> 
> ```
> wget http://archive.ubuntu.com/ubuntu/pool/main/o/openldap/libldap-2.4-2_2.4.45+dfsg-1ubuntu1_amd64.deb
> sudo dpkg -i libldap-2.4-2_2.4.45+dfsg-1ubuntu1_amd64.deb
> ```

This fixed it for me. I did get an error during the install that I had to fix with the following:
`sudo dpkg --configure -a`
`sudo apt-get -f install`

**Comment by teekaytech** [comment]
> I was having the same issue of `tableplus: error while loading shared libraries: libldap_r-2.4.so.2: cannot open shared object file: No such file or directory` and I managed to **solve** it by installing libldap manually from: https://ubuntu.pkgs.org/18.04/ubuntu-main-amd64/libldap-2.4-2_2.4.45+dfsg-1ubuntu1_amd64.deb.html
> 
> ```
> wget http://archive.ubuntu.com/ubuntu/pool/main/o/openldap/libldap-2.4-2_2.4.45+dfsg-1ubuntu1_amd64.deb
> sudo dpkg -i libldap-2.4-2_2.4.45+dfsg-1ubuntu1_amd64.deb
> ```

Thanks for this. I got an error in the process to install `libgssapi3-heimdal`. So I used the following:
- `apt-get install libgssapi3-heimdal`
- `apt --fix-broken install`

**Comment by huyphams** [comment]
Fixed: https://github.com/TablePlus/TablePlus-Linux/issues/131
