### ISSUE TITLE
Unable to connect to a remote PostgreSQL database

### ISSUE THREAD

**Issue by Elrendio** [TablePlus/TablePlus-Linux#14]
1. Database version (Ex: PostgreSQL 10.0):
PostgreSQL 10.6
2. TablePlus version (the number on the welcome or about screen, Ex: build 81):
Build 20
3. Linux distro (Ex: Ubuntu 18.04): 
ArchLinux
4. The steps to reproduce this issue:
a - Launch TablePlus with dmenu
b - Click on the `+` on the lower left to add a connection
c - Enter a name (Ex. Test DB)
d - Select `PostgreSQL` as database type
e - Select a color
f - Enter host (Ex my-database.eu-west-1.rds.amazonaws.com)
g - Enter user, password and database (Ex master, my-password and main)
h - Click on `Test` or `Connect` 
=> Error `fd_sendauth: no password supplied`

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
It seems like that the issue was the server side issue. You're trying to connect to a peer or local user only. Maybe you should try again with the SSH Tunnel.

**Comment by lmindwarel** [comment]
Hi,
Same problem here on Ubuntu. For localhost database with basic configuration. 
Same configuration work on others database tools.

**Comment by huyphams** [comment]
Are you using MySQL or PostgreSQL @lmindwarel ? it seems like that your application uses socket which is not supported by TablePlus at the moment.

**Comment by lmindwarel** [comment]
> 
> 
> Are you using MySQL or PostgreSQL @lmindwarel ? it seems like that your application uses socket which is not supported by TablePlus at the moment.

I use PostgreSQL. TablePlus work fine with MySQL on the same computer.

**Comment by jesseadams** [comment]
I am having the same issue trying to connect to Amazon RedShift using the PostgreSQL database type

**Comment by Elrendio** [comment]
Hello !

Any news on this ? It completely prevents me to use TablePlus :(

Thanks !

**Comment by huyphams** [comment]
the error `fd_sendauth: no password supplied ` seems like a miss config issue rather than a TablePlus issue. Can you share the connection setting here or send it to my email nick@tableplus.com please @Elrendio ? also please try to replace localhost with 127.0.0.1 and see how's thing going.

**Comment by lmindwarel** [comment]
it doesn't work either with 127.0.0.1. Something strange is that password disappears when button "test" was clicked, and after the dialog message show up "fe_sendauth: no password supplied".
I've tested to change password length, or don't use special characters, nothing work.

**Comment by huyphams** [comment]
it seems like you're facing this issue: https://github.com/TablePlus/TablePlus-Linux/issues/27 could you double-check this @lmindwarel thank you for the extra info!

**Comment by lmindwarel** [comment]
Yes ! It work now, installing gnome-keyring resolve the issue (i'm on kde too).
Strange because others drivers like mysql work perfectly without this package.
Tanks :)

**Comment by Ten0** [comment]
If `gnome-keyring` is a dependency of this package, then it should be specified as such in the `PKGBUILD`.

**Comment by Elrendio** [comment]
Once `gnome-keyring` was installed it worked like a charm.

**Comment by eleijonmarck** [comment]
hmm I am connecting fine to a redshift instance. We are using passwords and no SSL

**Comment by Ten0** [comment]
Why is this closed even though the missing dependency is still not added?

**Comment by huyphams** [comment]
I've released the new release 38 today and added a gnome-keyring as a required package: https://deb.tableplus.com/debian/dists/tableplus/main/binary-amd64/Packages

**Comment by huyphams** [comment]
You're using the Arch Linux, which is not officially supported at the moment. so it's not only the one that missing @Ten0 we will support other distros when it reaches the beta release.

**Comment by Ten0** [comment]
Right, but I thought this issue was related to it not working on Arch.

**Comment by xcorshinex** [comment]
@huyphams so what about now? does it supports arch linux now mate?

**Comment by dvkndn** [comment]
@xcorshinex please take a look at #3 :D there's a PKGBUILD there that you can try

**Comment by xcorshinex** [comment]
@dvkndn Thanks :D
