### ISSUE TITLE
Filter Not Working 

### ISSUE THREAD

**Issue by dwickycandralesmana** [TablePlus/TablePlus-Linux#140]
### Please answer the questions below, it helps us to track the issue.
Hi TablePlus Team, I found a bug, or maybe TablePlus currently doesn't support percona when I am going to use filter data. No matter what I type in that filter, this popup always shows.

![Screenshot from 2022-01-28 23-09-24](https://user-images.githubusercontent.com/52897634/151571407-174e8bba-68ae-4b51-a79e-6376f22e7aa7.png)

1. Database version (Ex: PostgreSQL 10.0):
Percona Server for MySQL version 8.0.26

2. TablePlus version (the number on the welcome or about screen, Ex: build 81):
TablePlus 0.1 (178) Alpha Release

3. Linux distro (Ex: Ubuntu 18.04):
Ubuntu 20.04

4. The steps to reproduce this issue:
a. Open Table
b. Add filters
c. Apply filters

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @dwickycandralesmana the build 180 should fix this issue. Thanks!

**Comment by dwickycandralesmana** [comment]
Thanks, it worked!
