### ISSUE TITLE
Apt-key deprecated, plus hard to install on a kali linux machine.

### ISSUE THREAD

**Issue by theghostmac** [TablePlus/TablePlus-Linux#142]
### Please answer the questions below, it helps us to track the issue.

1. Database version (Ex: PostgreSQL 10.0): PostgreSQL 14

2. TablePlus version (the number on the welcome or about screen, Ex: build 81):

3. Linux distro (Ex: Ubuntu 18.04):  Kali 2022a

4. The steps to reproduce this issue: run wget -qO - http://deb.tableplus.com/apt.tableplus.com.gpg.key | sudo apt-key add -

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by wout** [comment]
I'm having a similar issue:

```
...
E: The repository 'https://deb.tableplus.com/debian/20 tableplus Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by earlev4** [comment]
> I'm having a similar issue:
> 
> ```
> ...
> E: The repository 'https://deb.tableplus.com/debian/20 tableplus Release' no longer has a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> ```

Good day to everyone! 

I am having the same issue. Not sure if this is helpful, but I checked the following repository:

https://deb.tableplus.com/debian/

Looks like the directory for '20' is missing, but directories for '18' and '21' exist. In addition, the file modification dates reflect '11-Mar-2022 '.

Thanks so much!

**Comment by huyphams** [comment]
Hey sorry, it is a bug in the build script, I just fixed it and added the Directory 20 back.

**Comment by wout** [comment]
Thanks @huyphams. It's fixed now.

**Comment by earlev4** [comment]
Thanks so much, @huyphams!!! Much appreciated!

**Comment by Developer-Rezwan** [comment]
@huyphams How to do this..please help me
