### ISSUE TITLE
tableplus_0.1.178_amd64.deb uses unknown compression for member 'control.tar.zst', giving up

### ISSUE THREAD

**Issue by scrlkx** [TablePlus/TablePlus-Linux#144]
### Please answer the questions below, it helps us to track the issue.

This is probably not a TablePlus issue, I'd just like some help finding a solution.

1. Database version (Ex: PostgreSQL 10.0):

2. TablePlus version (the number on the welcome or about screen, Ex: build 81):
0.1.178 (I suppose)

3. Linux distro (Ex: Ubuntu 18.04): 
Debian 11 (bullseye)

4. The steps to reproduce this issue:
In a fresh Debian installation just follow the installation steps, when you reach the `sudo apt install tableplus` will face it.

Noted: If the bug is related to data, please attach an example SQL data.

Here is the output for `sudo apt install tableplus`:

```sh
dpkg-deb: error: archive '/var/cache/apt/archives/tableplus_0.1.178_amd64.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive /var/cache/apt/archives/tableplus_0.1.178_amd64.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 /var/cache/apt/archives/tableplus_0.1.178_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by sergiuprt** [comment]
there is an update to 0.1.182, go try it

**Comment by scrlkx** [comment]
Still broken.

```sh
dpkg-deb: error: archive '/var/cache/apt/archives/tableplus_0.1.182_amd64.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive /var/cache/apt/archives/tableplus_0.1.182_amd64.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 /var/cache/apt/archives/tableplus_0.1.182_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by sergiuprt** [comment]
you're installing via apt? I've installed it a few days ago and it worked from the first try (pop 21.10)
today updated, no issues

**Comment by scrlkx** [comment]
Yes, I'm installing via apt. Actually, I'm following the exactly [installation instructions](https://tableplus.com/blog/2019/10/tableplus-linux-installation.html).

Anyway, your answer helped me to understand the problem. It looks like Ubuntu 21 has released support for zstd compression ([see](https://news.itsfoss.com/ubuntu-21-10-release-schedule/)) and Debian 21 doesn't have that. I just run into the Ubuntu 20.04 install package (following the same instructions) and it worked.

Thank you @sergiuprt
