### ISSUE TITLE
Tableplus not working on Ubuntu 22.04

### ISSUE THREAD

**Issue by ianyxtan** [TablePlus/TablePlus-Linux#147]
1. Database version (Ex: PostgreSQL 10.0): 
Sqlite

3. TablePlus version (the number on the welcome or about screen, Ex: build 81):
TablePlus Linux Alpha

5. Linux distro (Ex: Ubuntu 18.04): 
Ubuntu 22.04

7. The steps to reproduce this issue:
Upgrade to Ubuntu 22.04 and found that tableplus is not working

**Comment by andergmartins** [comment]
It shows a sesgfault log for me:

```
Code: 1e fa 89 f8 31 d2 62 a1 fd 00 ef c0 09 f0 25 ff 0f 00 00 3d 80 0f 00 00 0f 8f 70 03 00 00 62 e1 fe 28 6f 0f 62 b2 75 20 26 d1 <62> f3 75 22 3f 0e 00 c5 fb 93 c9 ff c1 74 45 f3 0f bc d1 0f b6 04

tableplus[143278]: segfault at 7f8a64d9b9e0 ip 00007f8db078998c sp 00007f8da6ffc4b8 error 4 in libc.so.6[7f8db0600000+195000]
```

**Comment by andergmartins** [comment]
The following workaround worked for me: https://github.com/TablePlus/TablePlus-Linux/issues/148#issuecomment-1114325649

**Comment by ianyxtan** [comment]
@andergmartins Thanks for the reply. I've temporarily used Anteras and so far it's been working well. But I'll definitely try this solution out. 😃

**Comment by huyphams** [comment]
TablePlus for Ubuntu 22 has been released, please follow https://tableplus.com/linux/install

**Comment by bnussman** [comment]
Works great on Ubuntu Ubuntu 22.04.1 LTS! Thank you for fixing!
