### ISSUE TITLE
TablePlus not working on Ubuntu 22 (Segmentation fault)

### ISSUE THREAD

**Issue by Akkadius** [TablePlus/TablePlus-Linux#148]
### Please answer the questions below, it helps us to track the issue.

2. TablePlus version (the number on the welcome or about screen, Ex: build 81):

Latest available on repo

4. Linux distro (Ex: Ubuntu 18.04): 

```
cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 (Jammy Jellyfish)"
VERSION_CODENAME=jammy
```

5. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

https://gist.github.com/Akkadius/9dc0947acb07c288ff460dd75243cbb1

I've bought several licenses. Been using TablePlus primarily for years as I love it. Would be good to see more first class support for Linux considering the wave of people moving to Linux (Myself included) 

Otherwise I may have to finally shop for another browser

**Comment by lorenzo-moni** [comment]
I'm having the same issue

**Comment by drrwyy** [comment]
Workaround:

- Download https://archive.archlinux.org/packages/g/glib2/glib2-2.68.4-1-x86_64.pkg.tar.zst
- Extract `/usr/lib/libgio-2.0.so.0.6800.4` to `/opt/tableplus`
- Change `Exec` value in `/usr/share/applications/tableplus.desktop` to `Exec=env LD_PRELOAD=/opt/tableplus/libgio-2.0.so.0.6800.4 /usr/local/bin/tableplus`
- sudo update-desktop-database
- sudo gtk-update-icon-cache

based on here [https://aur.archlinux.org/packages/tableplus/#comment-827858](https://aur.archlinux.org/packages/tableplus/#comment-827858)

**Comment by balcieren** [comment]
I have too same issue

**Comment by KB885** [comment]
> Workaround:
> 
> * Download https://archive.archlinux.org/packages/g/glib2/glib2-2.68.4-1-x86_64.pkg.tar.zst
> * Extract `/usr/lib/libgio-2.0.so.0.6800.4` to `/opt/tableplus`
> * Change `Exec` value in `/usr/share/applications/tableplus.desktop` to `Exec=env LD_PRELOAD=/opt/tableplus/libgio-2.0.so.0.6800.4 /usr/local/bin/tableplus`
> * sudo update-desktop-database
> * sudo gtk-update-icon-cache
> 
> based on here https://aur.archlinux.org/packages/tableplus/#comment-827858

This works. Thanks. :+1:

**Comment by giancarloerra** [comment]
Confirming not working on Ubuntu 22.04 will try workaround

**Comment by Jaserto** [comment]
> Workaround:
> 
>     * Download https://archive.archlinux.org/packages/g/glib2/glib2-2.68.4-1-x86_64.pkg.tar.zst
> 
>     * Extract `/usr/lib/libgio-2.0.so.0.6800.4` to `/opt/tableplus`
> 
>     * Change `Exec` value in `/usr/share/applications/tableplus.desktop` to `Exec=env LD_PRELOAD=/opt/tableplus/libgio-2.0.so.0.6800.4 /usr/local/bin/tableplus`
> 
>     * sudo update-desktop-database
> 
>     * sudo gtk-update-icon-cache
> 
> 
> based on here https://aur.archlinux.org/packages/tableplus/#comment-827858

Works for me. I made a mistake and that's why it didn't work, I didn't put the space between ...6800.4 and /usr... In case it happens to anyone.

**Comment by dyaskur** [comment]
I downloaded  glib2, but can't found /usr/lib/libgio-2.0.so.0.6800.4? where is it?

**Comment by Jaserto** [comment]
@dyaskur First, make sure you have downloaded the correct file. You have to extract the file, right click, extract and you will find the _/usr_ folder.

**Comment by mayanksdudakiya** [comment]
Same here not working for me. When new tableplus version will be launched for ubuntu 22.04LTS?

**Comment by nikelborm** [comment]
Table plus for Linux is not even the beta. It is alpha. We need to rejoice that at least it is.

[original](https://tableplus.com/blog/2019/10/tableplus-linux-installation.html)

![Screenshot_20220725_162508](https://user-images.githubusercontent.com/29357907/180788011-5741660b-72f5-4f14-8e17-9f012505de36.png)

**Comment by SujeetKumar-zs** [comment]
> * tableplus

can yot tell the command to extract libgo file  to opt/tableplus

**Comment by thetnaingtun3** [comment]
> * Download https://archive.archlinux.org/packages/g/glib2/glib2-2.68.4-1-x86_64.pkg.tar.zst
> * Extract `/usr/lib/libgio-2.0.so.0.6800.4` to `/opt/tableplus`
> * Change `Exec` value in `/usr/share/applications/tableplus.desktop` to `Exec=env LD_PRELOAD=/opt/tableplus/libgio-2.0.so.0.6800.4 /usr/local/bin/tableplus`
> * sudo update-desktop-database
> * sudo gtk-update-icon-cache
> 
> based on here https://aur.archlinux.org/packages/tableplus/#comment-827858


This works. Thanks.

**Comment by huyphams** [comment]
TablePlus for Ubuntu 22 has been released, please follow https://tableplus.com/linux/install

**Comment by onattech** [comment]
Installed the latest(v188) and now TablePlus doesn't start for me again on Mint 21(Ubuntu 22.04). Back to v186 with drrwyy's workaround.

**Comment by thejspr** [comment]
Uninstalled, added the Ubuntu 22.04 repo from https://tableplus.com/linux/install, and reinstalled got rid of the segfault for me.

**Comment by curtsheller** [comment]
Uninstalled and reinstalled and still not worling. Getting 

```
425060 segmentation fault (core dumped)  tableplus
```

Pop!_OS 22.04 LTS x86_64
5.19.0-76051900-generic

**Comment by tr1ms** [comment]
> Workaround:
> 
> * Download [archive.archlinux.org/packages/g/glib2/glib2-2.68.4-1-x86_64.pkg.tar.zst](https://archive.archlinux.org/packages/g/glib2/glib2-2.68.4-1-x86_64.pkg.tar.zst)
> * Extract `/usr/lib/libgio-2.0.so.0.6800.4` to `/opt/tableplus`
> * Change `Exec` value in `/usr/share/applications/tableplus.desktop` to `Exec=env LD_PRELOAD=/opt/tableplus/libgio-2.0.so.0.6800.4 /usr/local/bin/tableplus`
> * sudo update-desktop-database
> * sudo gtk-update-icon-cache
> 
> based on here [aur.archlinux.org/packages/tableplus/#comment-827858](https://aur.archlinux.org/packages/tableplus/#comment-827858)

This workaround worked for me at first until it started crashing again with a segfault, but  when I launch it from `/usr/share/applications/tableplus.desktop` it seems to work fine

**Comment by curtsheller** [comment]
Tried it today and new version 0.1 (190) is not crashing right after starting.

**Comment by SupianIDz** [comment]
> Workaround:
> 
> * Download https://archive.archlinux.org/packages/g/glib2/glib2-2.68.4-1-x86_64.pkg.tar.zst
> * Extract `/usr/lib/libgio-2.0.so.0.6800.4` to `/opt/tableplus`
> * Change `Exec` value in `/usr/share/applications/tableplus.desktop` to `Exec=env LD_PRELOAD=/opt/tableplus/libgio-2.0.so.0.6800.4 /usr/local/bin/tableplus`
> * sudo update-desktop-database
> * sudo gtk-update-icon-cache
> 
> based on here https://aur.archlinux.org/packages/tableplus/#comment-827858

Work on Kali Linux 2022.4
