### ISSUE TITLE
Segfault on New Tab

### ISSUE THREAD

**Issue by wastrachan** [TablePlus/TablePlus-Linux#15]
1. Database version (Ex: PostgreSQL 10.0):
MySQL 5.6.45

2. TablePlus version (the number on the welcome or about screen, Ex: build 81):
Build 22

3. Linux distro (Ex: Ubuntu 18.04): 
Arch Linux (Kernel `5.4.2-arch1-1`)

4. The steps to reproduce this issue:

```
  1. Launch TablePlus 
  2. Connect to Database
  3. Open New Query Tab (Ctrl + T)
  4. Segmentation fault: [1]    2731 segmentation fault (core dumped)  tableplus
```

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Thanks, I just fixed it!
