### ISSUE TITLE
TablePlus not opening on Ubuntu 22 (Address boundary error)

### ISSUE THREAD

**Issue by brayann** [TablePlus/TablePlus-Linux#153]
### Please answer the questions below, it helps us to track the issue.

1. Database version 

2. TablePlus version (the number on the welcome or about screen, Ex: build 81): 0.1.186

3. Linux distro (Ex: Ubuntu 18.04): Ubuntu 22

4. The steps to reproduce this issue: Try to open TablePlus

After installing TablePlus on my Ubuntu 22, I got the following error when trying to open it:

```
Job 1, 'tableplus' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by augustobritodev** [comment]
i'm getting the same behavior here =(

**Comment by SteelWagstaff** [comment]
I attempted to open a previous installation of TablePlus (installed on Ubuntu 20.04) after upgrading to Ubuntu 22.04. I get a `Segmentation fault (core dumped)` error message.

**Comment by huyphams** [comment]
TablePlus for Ubuntu 22 has been released, please follow https://tableplus.com/linux/install

**Comment by brayann** [comment]
@huyphams thanks, it's working now.
Note for anyone that could face this: I had to remove the previous repositories from apt, and run `apt purge tableplus`, cause it kept installing the older version until I did those steps.

**Comment by huyphams** [comment]
Thank you for the feedback. I also found an issue where TablePlus could hang at startup 4/10 times on Ubuntu 22.04 (not sure why) I will try to fix it and release an update tomorrow.

**Comment by huyphams** [comment]
> Thank you for the feedback. I also found an issue where TablePlus could hang at startup 4/10 times on Ubuntu 22.04 (not sure why) I will try to fix it and release an update tomorrow.

It has been fixed now, please upgrade to the latest release 188.
