### ISSUE TITLE
Tableplus crashes when using autocomplete: vala_g_array_remove_index: assertion failed: (length > index)

### ISSUE THREAD

**Issue by romulo-iorio** [TablePlus/TablePlus-Linux#154]
### Please answer the questions below, it helps us to track the issue.

1. Database version (Ex: PostgreSQL 10.0):
- MariaDB 10.5.12/MySQL 8.0.23

2. TablePlus version (the number on the welcome or about screen, Ex: build 81):
- TablePlus 0.1 (190) - Alpha Release

3. Linux distro (Ex: Ubuntu 18.04): 
- Ubuntu 22.04.1 LTS

4. The steps to reproduce this issue:
- Basically it crashes when I select any option from autocomplete.

Noted: If the bug is related to data, please attach an example SQL data.
![Screenshot of error when I open it from the terminal, so I can see the logs](https://user-images.githubusercontent.com/36203794/190493405-52831d83-7c3b-45b7-8a9e-6a8a97b097a1.png)

**Comment by huyphams** [comment]
Hi @romulo-iorio do you have any special conditions, can you reproduce the issue now?

**Comment by romulo-iorio** [comment]
Hey @huyphams, I don't seem to have any special conditions.

And it's been happenning on any autocomplete option I select, so I can reproduce it with ease and anytime.

I've recorded a short video to show the issue happening, to see if it can help you figure it out :)

[Screencast from 16-09-2022 08:04:07.webm](https://user-images.githubusercontent.com/36203794/190625395-3781e9a8-ae42-401a-9c0c-d0ed1b363031.webm)

**Comment by huyphams** [comment]
Hi @romulo-iorio could you please try to update TablePlus 192 and see how it goes?

**Comment by romulo-iorio** [comment]
It's working now on 192, thank you!
