### ISSUE TITLE
Ubuntu 22 version seems to be missing lots of functionality

### ISSUE THREAD

**Issue by antoniobadia** [TablePlus/TablePlus-Linux#157]
### Please answer the questions below, it helps us to track the issue.

1. Database version (Ex: PostgreSQL 10.0): mysql  Ver 8.0.30-0ubuntu0.22.04.1 for Linux on x86_64 ((Ubuntu))

2. TablePlus version (the number on the welcome or about screen, Ex: build 81): 192

3. Linux distro (Ex: Ubuntu 18.04): Ubuntu 22.04

4. The steps to reproduce this issue:  start the application. Nothing seems to be like the images in the documentation. Lots of functionality missing (cannot import, drop table or database by right clicking, etc.).
![Screenshot from 2022-09-26 16-52-15](https://user-images.githubusercontent.com/12238237/192379360-c700d4eb-3531-4784-aac4-99d06dc34346.png)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by antoniobadia** [comment]
Just installed MySQL and Tableplus today (9/26/2022). Nothing seems to be like the images in the documentation. Lots of functionality missing (cannot import, drop table or database by right clicking, etc.).

**Comment by huyphams** [comment]
Hi @antoniobadia in the installation page, there is a note at the end:

```
Note:

- This is an alpha version.
- We will release an update every week, you can update it with the command:
sudo apt update && sudo apt upgrade
- It’s free without any limitation and it will remain completely free until out of beta.
- TablePlus is freemium application maintained by TablePlus team.
- Report bug, suggest feature and request other Linux distros here: [Issue tracker](https://github.com/TablePlus/tableplus-linux/issues)
```
It's an alpha build, not even reach the beta release so there are a lot of missing features.
