### ISSUE TITLE
installing tableplus on ubuntu 22.04

### ISSUE THREAD

**Issue by SuhaibMaraqa** [TablePlus/TablePlus-Linux#158]
### Please answer the questions below, it helps us to track the issue.

1. Database version (Ex: PostgreSQL 10.0):

2. TablePlus version (the number on the welcome or about screen, Ex: build 81):

3. Linux distro (Ex: Ubuntu 18.04): 22.04

4. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

when installing tableplus I got this error: 

sudo apt update
sudo apt install tableplus

The following packages have unmet dependencies:
 zlib1g-dev : Depends: zlib1g (= 1:1.2.11.dfsg-2ubuntu9) but 1:1.2.11.dfsg-2ubuntu9.1 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by apandada1** [comment]
Ubuntu pushed a minor update to the zlib1g package, but tableplus expects a specific version.
Maybe, remove the specific version requirement in the `debian/control` file of tableplus?

**Comment by huyphams** [comment]
Thanks let me check it.

**Comment by huyphams** [comment]
Hmm, we don't require or specific libz version anywhere in the source code. It could be a dependency of a gtk source code. Let me check which one wants the libz.

**Comment by apandada1** [comment]
It's good that you don't need the specific version in tge source code. The specific version might be there in the dependency section of the `debian/control` file which you created during packaging the app. You can remove the version number requirement in debian/control, and repackage.

**Comment by SuhaibMaraqa** [comment]
I am still kinda new to ubuntu enviroment, so how can I remove the specific version requirement in the debian/control file of tableplus?

**Comment by apandada1** [comment]
Can you paste the contents of the debian/control file of your debian source package?

**Comment by huyphams** [comment]
You can just install with the -f flag, it will ignore the error. I think TablePlus is still working.
sudo apt install -f tableplus

**Comment by SuhaibMaraqa** [comment]
Where can I find the debian/control file?

**Comment by SuhaibMaraqa** [comment]
it didn/t ignore the error, is there any other fixes?

**Comment by apandada1** [comment]
> Where can I find the debian/control file?

You don't have it (I thought I was replying to the package maintainer). The developers who packaged the app would have it.

@huyphams Can you please look into this?

**Comment by SuhaibMaraqa** [comment]
> Ubuntu pushed a minor update to the zlib1g package, but tableplus expects a specific version.
> Maybe, remove the specific version requirement in the `debian/control` file of tableplus?

How can I remove the specific version from the 'debian/control` file of tableplus?

**Comment by SuhaibMaraqa** [comment]
I downgraded to  1:1.2.11.dfsg-2ubuntu9 with 

$ sudo apt install zlib1g=1:1.2.11.dfsg-2ubuntu9

and it worked

**Comment by SuhaibMaraqa** [comment]
I downgraded to  1:1.2.11.dfsg-2ubuntu9 with 

$ sudo apt install zlib1g=1:1.2.11.dfsg-2ubuntu9

and it worked

**Comment by SuhaibMaraqa** [comment]
I downgraded to 1:1.2.11.dfsg-2ubuntu9 with

$ sudo apt install zlib1g=1:1.2.11.dfsg-2ubuntu9

and it got installed but Tableplus is not launching.

**Comment by asjur** [comment]
Still only providing a Deb package after all these years is peak laziness. If a small amount of time was spent to say set up a flatpak of tableplus, this would be a non-issue. It's not the first time TablePlus for linux has had dependency issues on it's extremely limited set of supported distros.
