### ISSUE TITLE
Can not open it on ubuntu 16.04 LTS. 

### ISSUE THREAD

**Issue by nameczz** [TablePlus/TablePlus-Linux#16]
1. Database version (Ex: PostgreSQL 10.0):
none
2. TablePlus version (the number on the welcome or about screen, Ex: build 81):
linux Alpha
3. Linux distro (Ex: Ubuntu 18.04): 
Ubuntu 16.04 LTS.  64bit.
4. The steps to reproduce this issue:
After install success, open tableplus, the icon flash for a seconds then disappear. 
Noted: If the bug is related to data, please attach an example SQL data.

**Comment by JustinR-FR** [comment]
Same issue with Linux Ubuntu 18.04.3 LTS.
All install process is good but when i click on icon nothing happen.
Say me if there are somes logs to give you :)

**Comment by huyphams** [comment]
You can type: tableplus in terminal to see the missing packages. then install those packages and it will work.

**Comment by JustinR-FR** [comment]
`libgee-0.8-2` was missing for me. Thanks !

**Comment by nameczz** [comment]
GLIBC_2.27 is missing for me. Mine is Ubuntu GLIBC 2.23-0ubuntu11. But it's quit hard for me to update it. May be will try it in furture. Thanks for your support. Closed Issue

**Comment by shivangi-ttn** [comment]
> Same issue with Linux Ubuntu 18.04.3 LTS.
> All install process is good but when i click on icon nothing happen.
> Tell me if there are somes logs to give you :)

+1
