### ISSUE TITLE
It's not changing the theme

### ISSUE THREAD

**Issue by mkevison** [TablePlus/TablePlus-Linux#160]
### Please answer the questions below, it helps us to track the issue.

1. Database version (Ex: PostgreSQL 10.0): Postgres 10

2. TablePlus version (the number on the welcome or about screen, Ex: build 81): 192

3. Linux distro (Ex: Ubuntu 18.04):  Ubuntu 22.04

4. The steps to reproduce this issue: 

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by dsentker** [comment]
Same with Ubuntu 23.04

**Comment by mkevison** [comment]
Fix
