### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by SuhaibMaraqa** [TablePlus/TablePlus-Linux#162]
### Please answer the questions below, it helps us to track the issue.

1. Database version (Ex: PostgreSQL 10.0):

2. TablePlus version (the number on the welcome or about screen, Ex: build 81): Tableplus 0.1 (192)

3. Linux distro (Ex: Ubuntu 18.04):  22.04

4. The steps to reproduce this issue:

when launching tableplus it says:

Segmentation fault (core dumped)

**Comment by huyphams** [comment]
same as https://github.com/TablePlus/TablePlus-Linux/issues/161
