### ISSUE TITLE
Apt-key Deprecation Warning on Ubuntu (with solution)

### ISSUE THREAD

**Issue by kalitvyan** [TablePlus/TablePlus-Linux#163]
TablePlus version 0.1 (192) Alpha

Ubuntu 22.04.01

The steps to reproduce this issue:
[TablePlus Linux Installation Guide](https://tableplus.com/blog/2019/10/tableplus-linux-installation.html), *Ubuntu 22.04* section

After the Installation try `apt-get update` and get warning:
```
W: https://deb.tableplus.com/debian/22/dists/tableplus/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
```

***The solution:***
1. Run `sudo apt-key list` and find Tableplus key

> pub   rsa4096 2019-11-26 [SC]
      2114 38D2 880D 8D98 E100  B141 2A17 818B 3877 2786
uid           [ unknown] TablePlus (Release key) <nick@tableplus.com>
sub   rsa4096 2019-11-26 [E]

2. Copy the last 8 characters from the second line. `3877 2786` in my case. Drop the space between the 8 characters.

3. Run the following command:
`sudo apt-key export 38772786 | sudo gpg --dearmour -o /etc/apt/trusted.gpg.d/tableplus.gpg`

4. `sudo apt-get update` 

Enjoy!

**Comment by huyphams** [comment]
Thanks @kalitvyan let me update those instructions.

**Comment by huyphams** [comment]
I've updated it to

wget -qO - https://deb.tableplus.com/apt.tableplus.com.gpg.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/tableplus-archive.gpg
Thanks
