### ISSUE TITLE
libpcre3 Dependancy problem in Ubuntu 22.04

### ISSUE THREAD

**Issue by YoungMind1** [TablePlus/TablePlus-Linux#164]
Linux distro: Ubuntu 22.04
I tried to follow the [Linux installation guide](https://tableplus.com/blog/2019/10/tableplus-linux-installation.html); But there seems to be dependency problem with Ubuntu's one.

`libpcre3-dev : Depends: libpcre3 (= 2:8.39-13ubuntu0.22.04.1) but 2:8.44-2+ubuntu20.04.1+deb.sury.org+1 is to be installed`

**Comment by bacalazin** [comment]
Same issue here when trying to install it on ubuntu 22 inside wsl2:
`sudo  apt -y install libnotify-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libpcre3-dev : Depends: libpcre3 (= 2:8.39-13ubuntu0.22.04.1) but 2:8.44-2+ubuntu20.04.1+deb.sury.org+1 is to be installed
E: Unable to correct problems, you have held broken packages.`

**Comment by a4abs** [comment]
I am also having the same issue on Ubuntu 22.04.1 LTS

`The following packages have unmet dependencies:
 libpcre3-dev : Depends: libpcre3 (= 2:8.39-13ubuntu0.22.04.1) but 2:8.44-2+ubuntu20.04.1+deb.sury.org+1 is to be installed
 libxml2-dev : Depends: libxml2 (= 2.9.13+dfsg-1ubuntu0.1) but 2.9.14+dfsg-0+ubuntu20.04.1+deb.sury.org+1 is to be installed
E: Unable to correct problems, you have held broken packages.
`

**Comment by bacalazin** [comment]
What I did to fix my issue was to downgrade the version of "libpcre3" to the version of ubuntu 22.
`sudo apt-get install libpcre3=2:8.39-13ubuntu0.22.04.1`
Fixed my issue

**Comment by Sultanul-Arefin** [comment]
> What I did to fix my issue was to downgrade the version of "libpcre3" to the version of ubuntu 22. `sudo apt-get install libpcre3=2:8.39-13ubuntu0.22.04.1` Fixed my issue

I had a similar problem when I was trying to install table plus in ubuntu 22.04. I had 3 issues with libcre3, libcre2, and libxml2. Fixed it with the following command.
