### ISSUE TITLE
The following packages have unmet dependencies: libglib2.0-dev & libgtk-3-dev

### ISSUE THREAD

**Issue by Mohamed1Gohar** [TablePlus/TablePlus-Linux#168]
sudo apt install tableplus
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libglib2.0-dev : Depends: libglib2.0-0 (= 2.72.1-1) but 2.72.4-0ubuntu1 is to be installed
                  Depends: libglib2.0-bin (= 2.72.1-1)
                  Depends: libglib2.0-dev-bin (= 2.72.1-1)
                  Depends: libpcre3-dev (>= 1:8.31) but it is not going to be installed
                  Depends: zlib1g-dev but it is not going to be installed
 libgtk-3-dev : Depends: gir1.2-gtk-3.0 (= 3.24.33-1ubuntu1) but 3.24.33-1ubuntu2 is to be installed
                Depends: libatk-bridge2.0-dev (>= 2.15.1) but it is not going to be installed
                Depends: libcairo2-dev (>= 1.14.0) but it is not going to be installed
                Depends: libfontconfig1-dev
                Depends: libfribidi-dev (>= 0.19.7) but it is not going to be installed
                Depends: libgdk-pixbuf-2.0-dev (>= 2.40.0) but it is not going to be installed or
                         libgdk-pixbuf2.0-dev (>= 2.40.0) but it is not going to be installed
                Depends: libpango1.0-dev (>= 1.44.0) but it is not going to be installed
                Depends: libwayland-dev (>= 1.9.91) but it is not going to be installed
                Depends: libgtk-3-0 (= 3.24.33-1ubuntu1) but 3.24.33-1ubuntu2 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by gxanshu** [comment]
Any solution ? i'm facing the same problem
