### ISSUE TITLE
Font color of NULL and EMPTY values

### ISSUE THREAD

**Issue by joonis** [TablePlus/TablePlus-Linux#177]
I would like to see a faded font color of `NULL` and `EMPTY` values. It would make the view clearer.

**Comment by huyphams** [comment]
We've fixed in the next update.

<img width="508" alt="Screenshot 2023-03-09 at 10 30 23 PM" src="https://user-images.githubusercontent.com/3654622/224072720-acad45b0-1b3f-4bd7-9db2-14a7343ff2e4.png">
