### ISSUE TITLE
Unable to enter license

### ISSUE THREAD

**Issue by wout** [TablePlus/TablePlus-Linux#178]
### Please answer the questions below, it helps us to track the issue.

1. Database version (Ex: PostgreSQL 10.0): N/A

2. TablePlus version (the number on the welcome or about screen, Ex: build 81): 0.1 (204) (Trial Beta)

4. Linux distro (Ex: Ubuntu 18.04): elementary OS 7 (based on Ubuntu 20.04 LTS)

5. The steps to reproduce this issue:
 
After entering the license key, this is the error message I get:

![image](https://user-images.githubusercontent.com/107324/224543566-2c519f66-bf66-466d-b49c-ccb11dea118d.png)

Tried updating the app but it seems to be at the latest version.

**Comment by huyphams** [comment]
Ah thanks, please try again it should work now @wout

**Comment by wout** [comment]
That worked, thanks for your quick reply!
