### ISSUE TITLE
Updated to tableplus-0.0.1-212.x86_64  - Application Icon Gone and Won't run

### ISSUE THREAD

**Issue by darkufo** [TablePlus/TablePlus-Linux#180]
### Please answer the questions below, it helps us to track the issue.

1. Database version (Ex: PostgreSQL 10.0): N/A

2. TablePlus version (the number on the welcome or about screen, Ex: build 81): tableplus-0.0.1-212.x86_64

3. Linux distro (Ex: Ubuntu 18.04):  Fedora 37

4. The steps to reproduce this issue:

Tableplus updated today to tableplus-0.0.1-212.x86_64

After Updating and Reboot, the Icon on the taskbar disappeared. Trying to run tableplus from the comman line fails with command not found.

it has also disappeared from the Application Launcher.

Is there anything I can do?

**Comment by huyphams** [comment]
Hi @darkufo please try to remove and then install the app again.

Think there were a missconfig script but we could not fix it on th old build.

sudo yum remove tableplus 
sudo yum install tableplus

would solve the issue
