### ISSUE TITLE
databases titles are mixedover when having a multiple workspace 

### ISSUE THREAD

**Issue by aliymahmoud** [TablePlus/TablePlus-Linux#186]
### Please answer the questions below, it helps us to track the issue.

1. Database version (Ex: PostgreSQL 10.0): mysql 8.0.82, mysql 8.0.32 (haven't tried with other versions)

2. TablePlus version (the number on the welcome or about screen, Ex: build 81): 0.1 (216)

3. Linux distro (Ex: Ubuntu 18.04): fedora 38

4. The steps to reproduce this issue: create new workspace while having an existing connection, save the new connection in the new workspace, the two workspaces now have the same title in title's bar as the last saved connection

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Fixed on our latest release.
