### ISSUE TITLE
Workspace button is light in light theme

### ISSUE THREAD

**Issue by wout** [TablePlus/TablePlus-Linux#187]
### Please answer the questions below, it helps us to track the issue.

1. Database version (Ex: PostgreSQL 10.0):

N/A

2. TablePlus version (the number on the welcome or about screen, Ex: build 81):

![image](https://github.com/TablePlus/TablePlus-Linux/assets/107324/f82875f8-b1b7-4f77-99e1-3e3db7b98393)

3. Linux distro (Ex: Ubuntu 18.04): 

![image](https://github.com/TablePlus/TablePlus-Linux/assets/107324/7ba26714-3390-411f-afa2-cb438be2dbc1)

4. The steps to reproduce this issue:

![image](https://github.com/TablePlus/TablePlus-Linux/assets/107324/d800dd76-6629-467c-8dcc-31d78d52dfa6)

**Comment by huyphams** [comment]
Thanks, it should be fixed in the next update.

**Comment by huyphams** [comment]
It's released now.
