### ISSUE TITLE
Filters options doesnt exist anymore

### ISSUE THREAD

**Issue by EduNowell** [TablePlus/TablePlus-Linux#188]
### Please answer the questions below, it helps us to track the issue.

1. Database version: MySql 5.7.31

2. TablePlus version: 0.0.4 ( 220 )

3. Linux distro: Ubuntu 20.04

4. The steps to reproduce this issue:

 - Open any table
 - Click on filters
 - In the last verion i could open a dropdown menu which have options like "=" or ">" but this menu had dissapear

![image](https://github.com/TablePlus/TablePlus-Linux/assets/58434883/bf02af59-3ef4-42ea-abd2-10633ad3d701)

**Comment by huyphams** [comment]
Ops sorry @EduNowell I just release an update to fix it, please update TablePlus. It should work now. Let me know if you're still seeing it.

**Comment by EduNowell** [comment]
> Ops sorry @EduNowell I just release an update to fix it, please update TablePlus. It should work now. Let me know if you're still seeing it.

Thank you so much!, i was going crazy with this
