### ISSUE TITLE
Failed to fetch https://deb.tableplus.com/debian/22/dists/tableplus/InRelease

### ISSUE THREAD

**Issue by jackfido** [TablePlus/TablePlus-Linux#189]
This error ocurrs when I try to update my system, as you know, Ubuntu check all the apt packages, and at this moment it is receiving a warning:

Failed to fetch https://deb.tableplus.com/debian/22/dists/tableplus/InRelease  Connection failed [IP: 2606:4700:3108::ac42:2b4d 443]

and of course it is a time out in that URL

**Comment by huyphams** [comment]
Ops sorry, I was changing the server ssl certification yesterday and it broke the download page. Just fixed it.
