### ISSUE TITLE
A database gets selected by default, even though the connection settings specify none

### ISSUE THREAD

**Issue by nerdo** [TablePlus/TablePlus-Linux#19]
1. Database version (Ex: PostgreSQL 10.0):
MySQL 5.7.25

2. TablePlus version (the number on the welcome or about screen, Ex: build 81):
build 24

3. Linux distro (Ex: Ubuntu 18.04): 
Pop_OS! 19.10

4. The steps to reproduce this issue:
* Set up a new connection to a MySQL database, without specifying a default database
* Connect to the DB server
* A database gets selected by default anyway

Since I'm only using this beta on my local and not yet in production, it's not a huge issue, but the reason I never specify a default database is to avoid enumerating a large number of tables on some production databases, where it typically causes  SQL clients to grind to a halt.

**Comment by huyphams** [comment]
it should work by now.
