### ISSUE TITLE
Could not open the app on Ubuntu 23.04

### ISSUE THREAD

**Issue by hiroyamaguch** [TablePlus/TablePlus-Linux#190]
### Please answer the questions below, it helps us to track the issue.

1. Database version (Ex: PostgreSQL 10.0): MySQL 5.7

2. TablePlus version (the number on the welcome or about screen, Ex: build 81): 226

3. Linux distro (Ex: Ubuntu 18.04): Ubuntu 23.04

4. The steps to reproduce this issue: Install and launch

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by hiroyamaguch** [comment]
When try to open i receive this message: 

`tableplus: error while loading shared libraries: libbson-1.0.so.0: cannot open shared object file: No such file or directory`

**Comment by ograciano** [comment]
the bug persist in ubuntu 22.04

**Comment by ograciano** [comment]
the solution is install the libraries missing 

`sudo apt install libmysqlclient*`
`sudo apt install libmongoc-*`
`sudo apt install libbson-*`

reguards

**Comment by huyphams** [comment]
Hi, please update the app again and it should works.

**Comment by huyphams** [comment]
sudo apt update && sudo apt install tableplus 

to update the app.
