### ISSUE TITLE
Query Parameters for Linux Client

### ISSUE THREAD

**Issue by disambiguationuk** [TablePlus/TablePlus-Linux#193]
Is there any indication of when [Query Parameters](https://docs.tableplus.com/query-editor/query-parameters) might be available on the Linux Client? I love TablePlus but it's getting to the point where I can't really use it for more than basic queries because of this missing feature.

**Comment by dmahalban** [comment]
Agreed. I've used this feature on the Mac and it's great. Being on Linux now, I was looking at purchasing for Linux but without this feature, I can't justify buying TablePlus.

**Comment by huyphams** [comment]
It's supported on the release 256!
