### ISSUE TITLE
Running queries or viewing large tables freezes/crashes the application

### ISSUE THREAD

**Issue by ipmanlk** [TablePlus/TablePlus-Linux#194]
### Please answer the questions below, it helps us to track the issue.

1. Database version (Ex: PostgreSQL 10.0):
PlanetScale (MySQL Driver)

2. TablePlus version (the number on the welcome or about screen, Ex: build 81):
1.0.3 (238) 

3. Linux distro (Ex: Ubuntu 18.04): 
Manjaro Gnome 

4. The steps to reproduce this issue:
Try querying or navigating a large table on PlanetScale.

---
I experienced this when working with a large PlanetScale database. Surprisingly enough this didn't happen with my local MySQL server. I believe UI is freezing due to slow network requests. Table I used for testing contained roughly 100k rows. I experienced brief UI freezes and some crashes occasional crashes when executing queries.
 
Issue,
![image](https://github.com/TablePlus/TablePlus-Windows/assets/13213457/6ce86af1-a3f9-4760-a5e9-8fc9bc80ad36)

My current setup,
![image](https://github.com/TablePlus/TablePlus-Windows/assets/13213457/6fe8cfb9-5208-46d2-b16b-2ae56bb646d7)

**Comment by huyphams** [comment]
"It doesn't crash; it's loading the rows on the main thread. You're loading too many rows, but with very low networking. Background threading in C is a bit challenging, so it's not the top priority at the moment, which means it will fail most stress tests with low network. By the way, even with very low network, a background thread doesn't help anyway.
