### ISSUE TITLE
Sorting issue on Table Plus linux tables

### ISSUE THREAD

**Issue by zhivkoApo** [TablePlus/TablePlus-Linux#199]
### Please answer the questions below, it helps us to track the issue.

1. Database version (Ex: PostgreSQL 10.0): MySQL 8.0

3. TablePlus version (the number on the welcome or about screen, Ex: build 81): 1.1.6 (248) (Trial)

4. Linux distro (Ex: Ubuntu 18.04): (Ubuntu 22.04)

5. The steps to reproduce this issue:
Go onto some table, and try to sort by some column (clicking on the column).
Integer columns are not sorted like 1,2,3,4,5,6,7,8,9,10,11,12 but 1,10,11,2,3,4,5,6,7,8,9 etc (treated like strings)
![image](https://github.com/TablePlus/TablePlus-Linux/assets/66877019/49565ede-1681-4b59-be1d-0cc1430d3b43)

Also sorting is not applied to full data retrieved by sql query, but only the page that you are viewing, so if i click to sort descending, i will not take the latest record from all time, but rather from the current page.
This was not like this just a month ago.

**Comment by huyphams** [comment]
Hi, it is fixed in the build 250. Thanks

**Comment by huyphams** [comment]
You are using ubuntu so the command will be

sudo apt update
sudo apt install tableplus
