### ISSUE TITLE
Package not installable on Ubuntu 19.10

### ISSUE THREAD

**Issue by dnl-jst** [TablePlus/TablePlus-Linux#2]
I tried to install the alpha version using the guide here:

https://tableplus.com/blog/2019/10/tableplus-linux-installation.html

Unfortunately a dependency for the package can not be installed, so the whole installation process does not work:

![Screenshot from 2019-12-02 16-50-38](https://user-images.githubusercontent.com/712897/69974052-d1239f00-1524-11ea-9440-b8d69c25d898.png)

Thank you for your work!

**Comment by aurelijusrozenas** [comment]
Same here: Ubuntu 19.10, kernel 5.3.0-23-generic

**Comment by huyphams** [comment]
I'm working on it, still downloading 😅
<img width="263" alt="Screen Shot 2019-12-02 at 12 49 37 PM" src="https://user-images.githubusercontent.com/3654622/69978053-37e39100-1502-11ea-9bb7-1052d71fac0f.png">

**Comment by nielspeen** [comment]
Apparently libnm-glib is discontinued in favor of libnm: https://gitlab.freedesktop.org/NetworkManager/NetworkManager/commit/1de8383ad9fdfc8f552117e5d109bdfa7005634b

**Comment by huyphams** [comment]
Thank you @nielspeen I've updated the packages to libnm, please try again!

**Comment by aurelijusrozenas** [comment]
Yes, install worked!
But... it does not start:
>tableplus: error while loading shared libraries: libgtksourceview-3.0.so.1: cannot open shared object file: No such file or directory

**Comment by wastrachan** [comment]
Modern GTK ships with `gtksourceview4`. This will require `gtksourceview3` as a dependency.

**Comment by huyphams** [comment]
I see, TablePlus uses dynamic link for sourceview and drivers. But Ubuntu 18.04 and Ubuntu 19.10 use different paths. I will fix it in the next update, it should be static link or bundled with TablePlus packages.

**Comment by huyphams** [comment]
Here is how it looks on Ubuntu 19.10 I will release an update today. thank you!
![Screen Shot 2019-12-02 at 2 55 16 PM](https://user-images.githubusercontent.com/3654622/69986449-cc0a2400-1513-11ea-98d6-597e2d432d65.png)

**Comment by huyphams** [comment]
Hey guys, I've bundled the libmysqlclient.so.20 with TablePlus as a temporary solution.
Please run
```
sudo apt update && sudo apt upgrade 
```
to update the client.  The long term solution should be static link this lib.

**Comment by aurelijusrozenas** [comment]
Hey. Updated worked, now it TP launches :)
