### ISSUE TITLE
Window title does not update when exiting a DB

### ISSUE THREAD

**Issue by nerdo** [TablePlus/TablePlus-Linux#20]
1. Database version (Ex: PostgreSQL 10.0):
MySQL 5.7.25

2. TablePlus version (the number on the welcome or about screen, Ex: build 81):
build 24

3. Linux distro (Ex: Ubuntu 18.04): 
Pop_OS! 19.10

4. The steps to reproduce this issue:
* Connect to a database
* Click the power button to close that connection and return to the main screen
* Title retains the "DRIVER : DB : TABLE" label

**Comment by huyphams** [comment]
I just fixed this issue 1 minute ago 😄 The reason it was not updated because I observer the tab changing behavior, but if you do not open any tab or just 1 tab, it will not trigger the update after exiting the database.
