### ISSUE TITLE
Cannot find how to format SQL Queries

### ISSUE THREAD

**Issue by leflamm** [TablePlus/TablePlus-Linux#208]
### Please answer the questions below, it helps us to track the issue.

1. Database version (Ex: PostgreSQL 10.0): 15.7 

2. TablePlus version (the number on the welcome or about screen, Ex: build 81): Version 1.2.0 (254)

3. Linux distro (Ex: Ubuntu 18.04): Ubuntu 24.04

4. The steps to reproduce this issue:
  1. open TablePlus
  2. connect to some DB
  3. open new SQL query tab
  4. write down a particularly ugly query
  5. look for a format/prettify/beautify button - cannot find any, so no usual key combination seems to work either

Btw: I saw such a button on several screenshots which is the reason for my irritation. :v:

**Comment by ernstki** [comment]
@leflamm I think you might've seen a macOS screenshot. As @huyphams stated in #176, this is not a cross-platform app. It's separate apps.

You may find some of the suggestions in Sequel-Ace/Sequel-Ace#1227 helpful, though. To get specific, [jdorn/sql-formatter](https://github.com/jdorn/sql-formatter) does what it says on the tin, and with the right `xdotool` incantations, you might find a satisfactory workaround.

Here's my quick-and-dirty attempt:

![Animated GIF screencast of running 'sql-formatter' bound to a hotkey, on the active selection in an instance of the Mousepad text editor](https://github.com/user-attachments/assets/0ab8e625-0a54-4fa5-a707-939f9821299c)

I _tried_ to get `xdotool` to actually paste over the selection, but didn't have any luck with the obvious things, and this probably wouldn't work with Wayland anyway.

Good luck!

**P.S.:** The degree to which the macOS app and the Linux app appear to have feature-parity—including many of the shortcut keys, if you swap <kbd>⌘</kbd> for <kbd>Ctrl</kbd>—is frankly pretty amazing. So, cheers to the team for what they've been able to accomplish so far.

**Comment by huyphams** [comment]
It's now supported on the build 256
