### ISSUE TITLE
It would be great if you add Debian/Stable support for the repository.

### ISSUE THREAD

**Issue by orkhanfarmanli** [TablePlus/TablePlus-Linux#21]
Here's the return when I try to add the repository. My OS is Deepin Linux 15.11 which is based on Debian/stable.

```bash
$ sudo add-apt-repository "deb [arch=amd64] https://deb.tableplus.com/debian tableplus main"
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 109, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 93, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Deepin/stable
`

**Comment by evansmwendwa** [comment]
Managed to install successfully on deepin but it crashes on launch

```
tableplus: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by tableplus)
tableplus: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by tableplus)
```

**Comment by maniadevice** [comment]
`add-apt-repository` failed to work for me too. I ran the following instead, and it was successful:

`echo "deb [arch=amd64] https://deb.tableplus.com/debian tableplus main" | sudo tee /etc/apt/sources.list.d/tableplus.list`

Hope it works for you.

**Comment by huyphams** [comment]
TablePlus will be distributed on all distro when it reaches the beta state. Currently, it's limited Ubuntu 18.04 and 19.04 only.
Thanks guy.

**Comment by dvkndn** [comment]
In the meantime, I think you may also [upgrade the lib yourself](https://github.com/TablePlus/TablePlus-Linux/issues/28#issuecomment-592924135)

**Comment by evansmwendwa** [comment]
I can confirm tableplus is working on deepin 20 beta
