### ISSUE TITLE
TablePlus resets license key after some time (Linux, Ubuntu)

### ISSUE THREAD

**Issue by mibeon** [TablePlus/TablePlus-Linux#213]
TablePlus resets the license key after a restart (on Linux, Ubuntu 24.10)

1. Database version (Ex: PostgreSQL 10.0): not related to this issue

2. TablePlus version (the number on the welcome or about screen, Ex: build 81): Version 1.2.1 (256)

3. Linux distro (Ex: Ubuntu 18.04): 24.10

4. The steps to reproduce this issue: Just open TablePlus, enter your valid license. TablePlus says "Thanks" and after a restart the key is reseted. Last week it was not the case. Now, every f.. time I have to enter the f.. license.

![tableplus_license_bug](https://github.com/user-attachments/assets/d70d558b-5ef5-4b10-bbfd-60d90b89d6ea)

**Comment by huyphams** [comment]
Hi @mibeon, could you email us at nick@tableplus.com with the license details? (Apologies, Nick is off for the weekend, so there might be a delay in response.)

**Comment by mibeon** [comment]
@huyphams Thanks for the reply. Email is out.

**Comment by mibeon** [comment]
@huyphams Any first findings about this bug with reseting TablePlus to the trial version?

**Comment by huyphams** [comment]
please up to the build 258 @mibeon it should solve the issue
