### ISSUE TITLE
Unable to decode \n

### ISSUE THREAD

**Issue by Root3287** [TablePlus/TablePlus-Linux#22]
1. Database version (Ex: PostgreSQL 10.0):
MariaDB 10.3.20

2. TablePlus version (the number on the welcome or about screen, Ex: build 81):
Build 24 (latest on what apt is reporting)

3. Linux distro (Ex: Ubuntu 18.04): 
Ubuntu->PopOS 19.10

4. The steps to reproduce this issue:
Noted: If the bug is related to data, please attach an example SQL data.

TablePlus have trouble decoding \n characters for database charset utf8mb4
![Screenshot from 2019-12-12 12-27-14](https://user-images.githubusercontent.com/1932945/70738779-083f4080-1cdb-11ea-9302-52e8354b6d6e.png)

Actual value
```json
{
  "left":[
    {
      "type": "disabled",
      "name": "Root3287",
      "link": "/",
      "loggedIn": true
    },
    {
      "type": "dropdown",
      "name": "Dropdown",
      "links": [
        {"type": "link", "name":"test", "link":"/test"},
        {"type": "divider"}
      ]
    }
  ],
  "right":[{
      "type": "dropdown",
      "name": "Guest",
      "loggedIn": false,
      "links": [
        {"type": "link", "name":"Register", "link":"/register/"},
        {"type": "divider"},
        {"type": "link", "name":"Login", "link":"/login/"}
      ]
    },{
      "type": "dropdown",
      "name": "user",
      "display":{"type":"username"},
      "loggedIn": true,
      "links": [
        {"type": "link", "name":"Admin", "link":"/admin/", "includeGroup":[1]},
        {"type": "link", "name":"Mod", "link":"/mod/", "excludeGroup":[1]},
        {"type": "divider"},
        {"type": "link", "name":"Log out", "link":"/logout/"}
      ]
    }]
}
```

Off Topic: Thank you for making TablePlus available for Linux. It definitely better than DataGrip (less bloat) or porting something with wine.

**Comment by huyphams** [comment]
Hey @Root3287 it must be a cache issue or something, We released TablePlus Linux build 26 a week ago, which has supported utf8mb4 already. Please check it out!

**Comment by Root3287** [comment]
Just updated to Build 26. Still an issue.

**Comment by huyphams** [comment]
Hmm, I'm not sure why it didn't work with MariaDB. I've MySQL 8 and it works fine. TablePlus Linux is also using the same Driver with TablePlus iOS/Windows/macOS which work fine with utf8mb4

**Comment by huyphams** [comment]
Now I got it. it's not related to the database driver. it seems like a limitation of the Linux Native View. which could not render the new line character.

**Comment by huyphams** [comment]
It's fixed in new build 32. Thanks.
