### ISSUE TITLE
Save icon not present in HiDPI mode

### ISSUE THREAD

**Issue by wout** [TablePlus/TablePlus-Linux#26]
1. Database version (Ex: PostgreSQL 10.0):
N/A

2. TablePlus version (the number on the welcome or about screen, Ex: build 81):
0.1.32

3. Linux distro (Ex: Ubuntu 18.04): 
elementary OS 5.1 (based on Ubuntu 18.04.3 LTS) 

4. The steps to reproduce this issue:
N/A

I am on a 4k (HiDPI) screen and the save icon is not showing:

![image](https://user-images.githubusercontent.com/107324/71640149-88bee480-2c7c-11ea-8594-022e58d6e509.png)

**Comment by huyphams** [comment]
Hi @wout thank you, could you check the new update 34, I've changed the icon in that build (those icons will be replace the future with a better design).

**Comment by wout** [comment]
@huyphams Great, thanks. It's fixed now.

As a side note, I am really enjoying TablePlus in Linux. It already replaced Sequeler in my workflow and I only open DBeaver if I need to do some import/export/sync. Can't wait to press that buy button once it has been released officially. :wink:

**Comment by huyphams** [comment]
Thank you @wout no worries, I will make the import/export in the next update!
