### ISSUE TITLE
Password seems to not stick on Kubuntu 19.10

### ISSUE THREAD

**Issue by joshbenham** [TablePlus/TablePlus-Linux#27]
1. Database version (Ex: PostgreSQL 10.0):
mysql  Ver 8.0.18-0ubuntu0.19.10.1 for Linux on x86_64 ((Ubuntu))

2. TablePlus version (the number on the welcome or about screen, Ex: build 81):
TablePlus (Alpha) Build 36

3. Linux distro (Ex: Ubuntu 18.04): 
Kubuntu 19.10

4. The steps to reproduce this issue:
Open up Table Plus
Put in your connection details (Username/Password)
Save or Test and the Password dissappears.

Noted: If the bug is related to data, please attach an example SQL data.

-----------------------------

Unfortunately there seems to be a bug where I try and log in but my password is not sticking...

The Logs I get are

```
** Message: 15:49:19.394: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
** Message: 15:49:19.664: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
Unable to get the SSH password from libsecret** Message: 15:49:19.664: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
Unable to get the SSH password from libsecret** Message: 15:49:19.666: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
Unable to get the SSH password from libsecret
```

Here is an gif showing how password disappears.

![ezgif-2-c587a0990800](https://user-images.githubusercontent.com/401672/71951394-052e6600-322f-11ea-8722-09e3ceda65a5.gif)

**Comment by huyphams** [comment]
Hi @joshbenham Thank you!, I did a google search and found out that it needs to be installed the package: gnome-keyring
I'm not sure if it helps, could you please try to install it?

**Comment by joshbenham** [comment]
Ok awesome. That worked straight away and luckily the dependencies were not too large for a KDE system.

```
gnome-keyring 
gnome-keyring-pkcs11 
libpam-gnome-keyring 
p11-kit 
p11-kit-modules
```

I assume that can be installed through the installer next time? 

Also thanks for the quick response. I will close the ticket now :)
