### ISSUE TITLE
tableplus: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by tableplus)

### ISSUE THREAD

**Issue by bautistavirchar** [TablePlus/TablePlus-Linux#28]
1. Database version (Ex: PostgreSQL 10.0): **won't open after installation.**

2. TablePlus version (the number on the welcome or about screen, Ex: build 81): ?

3. Linux distro (Ex: Ubuntu 18.04):  **16.04**

4. The steps to reproduce this issue: ?

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by fendiseptiawan0709** [comment]
I'm also have this problem. After install TablePlus on my machine, then it can't be open. Even using terminal or from start menu.
Then, I tried to open from terminal, it says :
```tableplus: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by tableplus)```
___

1. Database version : -

2. TablePlus version : Alpha Version

3. Linux Distro : Ubuntu 16.04 x64

4. Step to reproduce : Just open the TablePlus after installation finish.

___

I hope this problem will fixed soon. Thanks

**Comment by utkrist** [comment]
Same issue. Please fix.

**Comment by dvkndn** [comment]
Hi guys, sorry for the issue. For more information please see [this stackoverflow answer](https://superuser.com/questions/537683/how-to-fix-lib-x86-64-linux-gnu-libc-so-6-version-glibc-2-14-not-found/537694#537694) but the short version is that we compiled our app with a GLib version that is not available on your system.

A work around is to install the mentioned version yourself.

We're still in alpha, so we can't support all versions of Ubuntu yet, especially the old ones. However, moving forward, we are looking into ways to improve our distribution to avoid this issue.

**Comment by m-alishan** [comment]
Hi,
@bautistavirchar  can you please share the instructions to build table plus, I am using Linux mint 18.2 (Sonya) and want to build table plus for GLIBC 2.23, a guide or a head start will help.

**Comment by devvir** [comment]
Hi, still having this issue in August 2025. Linux Zorin.

```
uname -a
Linux x 6.8.0-64-generic #67~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Jun 24 15:19:46 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```
