### ISSUE TITLE
Export of table - Right click on tables does not display any options

### ISSUE THREAD

**Issue by eleijonmarck** [TablePlus/TablePlus-Linux#33]
1. Database version (Ex: PostgreSQL 10.0):
10.11
2. TablePlus version (the number on the welcome or about screen, Ex: build 81):
36
3. Linux distro (Ex: Ubuntu 18.04): 
19.10
4. The steps to reproduce this issue:
Right click on any table in the public schema

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by dvkndn** [comment]
Thanks @eleijonmarck ! Just a small update that we have implemented the Export feature for the query result, and we planned to put it in our upcoming release. Exporting a table will follow that.
