### ISSUE TITLE
Reloading data and structure of a table

### ISSUE THREAD

**Issue by wout** [TablePlus/TablePlus-Linux#35]
1. Database version (Ex: PostgreSQL 10.0):
N/A

2. TablePlus version:
Build 36

3. Linux distro:
elementary OS 5.1

4. The steps to reproduce this issue:
N/A

5. Description:
After creating a database migration, it is often required to reload a table. When a table is already open in a tab, it is not possible to reload it. The only fix now (afaik) is to close the app and re-open it again. A `ctrl + r` would be perfect.

**Comment by dvkndn** [comment]
Thanks @wout . Actually we have implemented the `ctrl + r` but some [are reporting](https://github.com/TablePlus/TablePlus-Linux/issues/36) it may not work some cases. We're looking into it.

In the meantime, you don't need to close the app, just the tab of that table (e.g. click on another table, then close the tab of the original table, then click on it)

I understand that this is just a work around. We're putting a refresh button on the header too, as mentioned in the linked issue

**Comment by dvkndn** [comment]
Hi @wout we've just released a new version :D it should make the `ctrl + r` more stable and also have an explicit reload button on the header. Can you try updating and see if it helps?

**Comment by wout** [comment]
@dvkndn Wow, what an update! Love the ability to switch to a light UI and the better buttons. And the `ctrl + r` works great, too.

Thanks for your work on this. I really love the app! :)
