### ISSUE TITLE
There is no way to refresh/refetch the data

### ISSUE THREAD

**Issue by canvural** [TablePlus/TablePlus-Linux#36]
1. Database version (Ex: PostgreSQL 10.0): Any

2. TablePlus version (the number on the welcome or about screen, Ex: build 81): Alpha build 36

3. Linux distro (Ex: Ubuntu 18.04): Ubuntu 19.10

4. The steps to reproduce this issue:

When I'm viewing the rows of a table, there is no way to refresh the data. Even switching to other table, and coming back to original one, doesn't work.

**Comment by huyphams** [comment]
Hi @canvural, please try Control + R or close and reopen the table, it should reload the content.

**Comment by canvural** [comment]
Hi,

I tried Ctrl + R. And it does not seem to work either.

**Comment by dvkndn** [comment]
Hi @canvural , we are adding a refresh button on header to make it's easier to refresh.

In the meanwhile:

> When I'm viewing the rows of a table, there is no way to refresh the data. Even switching to other table, and coming back to original one, doesn't work.

When switching between tables, it's only switching tabs, and no query is run again. To run the query again, you can try closing its tab before clicking on it.

> I tried Ctrl + R. And it does not seem to work either.

Does Ctrl + R works in other applications? For example, in the Files of Ubuntu, does pressing Ctrl + R give you a quick flashing/blinking of the content?

**Comment by aurelijusrozenas** [comment]
It works for me on 0.1 (Build 38), Ubuntu 19.10, Postgres 12, Mysql 8.
I have not ever noticed that it did not work.

**Comment by dvkndn** [comment]
We've just added a refresh button on the header, and do some improvement there. They will be available in the upcoming release:

![Screenshot from 2020-03-04 12-10-52](https://user-images.githubusercontent.com/5953369/75847238-3a12ff80-5e11-11ea-9c40-e6f9a29b3c07.png)

Hopefully that would make the refresh data more reliable and easier :D

**Comment by dvkndn** [comment]
Hi @canvural we've just released a new version :D it should make "ctrl + R" more reliable, and also has an explicit reload button on the header. Please try updating and see if it helps :D

**Comment by canvural** [comment]
Thank you very much! I'll try it later.
