### ISSUE TITLE
Feature request: Add search in tables column to quickly find a table.

### ISSUE THREAD

**Issue by wout** [TablePlus/TablePlus-Linux#38]
1. Database version (Ex: PostgreSQL 10.0):
N/A

2. TablePlus version (the number on the welcome or about screen, Ex: build 81):
Alpha Build 38 Linux

3. Linux distro (Ex: Ubuntu 18.04):
elementary OS 5.1

4. The steps to reproduce this issue:
It would be great to have a search field in the tables column on the left to quickly find a table. Some projects have many tables and scrolling is not always as convenient.

**Comment by dvkndn** [comment]
Thank you. That does seem to be useful :+1: we will definitely consider it.

**Comment by dvkndn** [comment]
Hi @wout , have you used the Mac version? There is an "Open anything" feature, which also allow you to type to search for a table and open it.

If we have that "Open anything" in the Linux version, may I assume that we will not need the search field any more?

**Comment by dvkndn** [comment]
Actually we will do both :D each has its own use case

**Comment by wout** [comment]
I'll need to check on my Mac. I actually bought TablePlus when I was evaluating Windows, but ultimately I decided to return to Linux. So, I am very grateful you are making the effort to create a Linux version. A straightforward database management tools for Linux is really missing, even if we have Sequeler on elementary OS. That's why I love TablePlus.

I's be grateful to have either one. But both would be even better. 😂️

**Comment by dvkndn** [comment]
Thank you!

**Comment by aurelijusrozenas** [comment]
My 2 cents why separate search for tables could be convenient: imagine you have multiple tables with similar name (e.g. `sthLog`), then it would nice to type `log` to filter tables and have list of only those tables. PhpMyAdmin has filter like that and it works great.
I have not used finished TablePlus because I am only on linux so I have no idea how it works fully implemented so I let my imagination run... :)

**Comment by dvkndn** [comment]
@aurelijusrozenas thank you. Yes it's sure we will support that :D

**Comment by beargroup-jay** [comment]
:+1: for the table filter, I use TablePlus on Mac with Magento development and there are many tables with similar names. Recently switched to Linux for my daily driver, and was very happy to see a Linux version!

I was unaware of the "Find Anything" command on MacOS TablePlus, but after experimenting with it a bit it is a nice feature but not a replacement for table filter. Thanks!

**Comment by carvemerson** [comment]
I'm a new user of TablePlus, and I'm missing this search on the columns list. 
Perhaps you can add a feature to go to the typed name, for instance, if I have 500 columns on a table, and want to get the owner_id, if I type 'ow' with the drop-down opened, it will be great to highlight the first column that have the 'ow', or filter only those columns that have this chars.

**Comment by carvemerson** [comment]
Another thing, perhaps you can add a search bar on the tables list, it will help a lot when you have hundreds of tables.

**Comment by wout** [comment]
> Another thing, perhaps you can add a search bar on the tables list, it will help a lot when you have hundreds of tables.

Isn't that the topic of this issue? :)

**Comment by carvemerson** [comment]
I don't think so. 
I think this topic is about this filters:
![image](https://user-images.githubusercontent.com/6718864/85460663-dc4e2300-b579-11ea-9744-d10de9cdd57d.png)

I'm talking about the table list, that is on left (or right) side of the data:
![image](https://user-images.githubusercontent.com/6718864/85460805-03a4f000-b57a-11ea-8a5c-09cdc843084e.png)

> > Another thing, perhaps you can add a search bar on the tables list, it will help a lot when you have hundreds of tables.
> 
> Isn't that the topic of this issue? :)

**Comment by wout** [comment]
@carvemerson No, it's in fact about the same thing. A search field for tables in the left column. ;)

**Comment by carvemerson** [comment]
Ah yes, indeed. :) You are right. Eheheh

**Comment by huyphams** [comment]
The build 69 supports search for items now

**Comment by huyphams** [comment]
The build 72 now has "search for items" and "search for columns".
<img width="1344" alt="file" src="https://user-images.githubusercontent.com/3654622/103066168-de597300-45ea-11eb-9631-f32af4d90f23.png">

**Comment by wout** [comment]
@huyphams Thank you so much for implementing this feature. 😍️

**Comment by beargroup-jay** [comment]
Very much appreciated, thanks @huyphams !
