### ISSUE TITLE
Crashes after manual update sql + refresh

### ISSUE THREAD

**Issue by aurelijusrozenas** [TablePlus/TablePlus-Linux#39]
1. Database version: Postgres 12, Sqlite, Mysql 8

2. TablePlus version: 0.1 (Build 38)

3. Linux distro: Ubuntu 19.10

4. The steps to reproduce this issue:
- Open any table to view data.
- Refresh (Ctrl + R) - works fine.
- Open new tab
- Run manual sql to change data, any of UPDATE/DELETE/DROP TABLE
- Open back first tab
- Refresh
- App crashes with `segmentation fault (core dumped)  tableplus`.
Not sure how to get more logs.

**Comment by dvkndn** [comment]
Thank you, I'm trying to reproduce that. It's a critical issue so sorry a lot :(

**Comment by aurelijusrozenas** [comment]
If you need more information and/or if there is a way to find logs somewhere, let me know. It's reproducible on my machine any time :)

**Comment by dvkndn** [comment]
Hi @aurelijusrozenas , thank to your report, we have identified the root cause and fixed it! We will release the fix very soon.

**Comment by dvkndn** [comment]
Hi @aurelijusrozenas sorry for the late reply and late release :( we got some hit with the covid virus..

Anyway, we've just released a new version that has the fix for this issue :D can you try update and see if it's fixed?

Sorry for the inconvenient

**Comment by aurelijusrozenas** [comment]
Hi @dvkndn yes, now it's working. Great!
However I found another bug... Will report as separate issue :)
