### ISSUE TITLE
Feature request: Copy row data

### ISSUE THREAD

**Issue by beargroup-jay** [TablePlus/TablePlus-Linux#41]
I imagine this is already on your list, but being able to copy row data (as sql insert, csv, plain text) is something I use a lot on MacOS TablePlus. Thanks for working on a Linux release!

**Comment by dvkndn** [comment]
Thank you! We will have it very soon :D We already have export to CSV in next release, that will help having copy row data soon

**Comment by huyphams** [comment]
It's added, thanks @beargroup-jay

**Comment by beargroup-jay** [comment]
thank you!
