### ISSUE TITLE
Query window does not select DB by default

### ISSUE THREAD

**Issue by aurelijusrozenas** [TablePlus/TablePlus-Linux#45]
1. Database version: Mysql 8
2. TablePlus version: 0.1 (Build 42)
3. Linux distro: Ubuntu 19.10
4. The steps to reproduce this issue:
- Open connection with default database set
- Open table to browse - all good
- Open new tab for sql
- Enter any sql (select will do)
- Run it
- I get message `No database selected`

I am pretty sure this was not the case before because I do not remember enter `use database` statement ever. I don't know maybe this is intended functionality but even if it is - in would be inconvenient.

**Comment by huyphams** [comment]
Thanks, it was a bug.
Workaround solution: enter the database name into the connection form. If you change the database in the dropdown you have to run the use database manually (TablePlus should do it, we will fix it.)

**Comment by huyphams** [comment]
It's fixed on the newest release 44.
