### ISSUE TITLE
Crash on Connection over SSH

### ISSUE THREAD

**Issue by wastrachan** [TablePlus/TablePlus-Linux#46]
1. Database version (Ex: PostgreSQL 10.0):

> MySQL 5.6.45

2. TablePlus version (the number on the welcome or about screen, Ex: build 81):

> 42

3. Linux distro (Ex: Ubuntu 18.04): 

> Arch Linux

4. The steps to reproduce this issue:

> 1. Connect to a database over an SSH tunnel
The following settings were used in the connection (and worked as recently as build 40):
```
{
        "id": "e594ad30-2eb5-4db1-a175-fdb445dadf55",
        "name": "Prod DB04",
        "color": "rgb(164,0,0)",
        "db-driver": "MySQL",
        "db-host": "",
        "db-port": "",
        "db-user": "root",
        "db-name": "test",
        "db-path": "",
        "use-ssh-tunnel": 1,
        "ssh-host": "db04.testdomain.com",
        "ssh-port": "30000",
        "ssh-user": "root",
        "ssh-key-path": "/home/winston/.ssh/id_rsa",
        "ssl-key-path-1": "",
        "ssl-key-path-2": "",
        "ssl-key-path-3": "",
        "selected-schema": "test"
    }
```
> 2. TablePlus crashes with the following:
```
➜ tableplus 
tableplus: /usr/lib/libldap_r-2.4.so.2: no version information available (required by tableplus)

(TablePlus:46801): Gtk-WARNING **: 16:19:12.094: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
[1]    46801 segmentation fault (core dumped)  tableplus
```

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by dvkndn** [comment]
Hi @wastrachan does it crash in both "Test" and "Connect" or just one of them?

**Comment by wastrachan** [comment]
“Test” works as intended, it only fails on “connect”.

**Comment by dvkndn** [comment]
Thank you :D let us look into it

**Comment by huyphams** [comment]
Hey @wastrachan I'm sorry about the crash, could you please update to the lasted release build 44 and see how it goes? Thank you

**Comment by wastrachan** [comment]
Yep! Confirmed working again in build 44!
