### ISSUE TITLE
Can't set value to NULL

### ISSUE THREAD

**Issue by emhagman** [TablePlus/TablePlus-Linux#48]
1. psql 10.7

2. Alpha Build 44

3. Manjaro [Arch Linux] 2020.03

4. Try to set a field to NULL. Clear the field (EMPTY) saves with syntax error. Setting to string NULL is just string, etc.

**Comment by huyphams** [comment]
Hi @emhagman please update to the build 46, we now can set null value via the right-click menu context.

**Comment by emhagman** [comment]
@huyphams Thanks for updating that so quickly! I bought a license for Windows to support this version!

**Comment by cesarvspr** [comment]
> Hi @emhagman please update to the build 46, we now can set null value via the right-click menu context.

What menu is that?

**Comment by cesarvspr** [comment]
Thank you for the answer @huyphams  but the set NULL menu works for existing rows. 

Sometimes when I copy a json and try to insert it gets converted to empty string instead of null. Idk if that is fixed in newer versions. I am on Version 5.4.0 (504)
