### ISSUE TITLE
Can't use 'NOW()' in datetime columns

### ISSUE THREAD

**Issue by ZayRTun** [TablePlus/TablePlus-Linux#49]
1. Database version (Ex: PostgreSQL 10.0):
MySQL 5.7.29
2. TablePlus version (the number on the welcome or about screen, Ex: build 81):
0.1 (Build 44)
3. Linux distro (Ex: Ubuntu 18.04): 
Ubuntu 18.04
4. The steps to reproduce this issue:

I can't use NOW() in DateTime columns. Maybe this feature is not yet implemented in this build. But I really hope that this gets implemented.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @ZayRTun please update to the build 46, it should work now.

**Comment by ZayRTun** [comment]
HI, I just updated to build 46, but still it's not working.

![tableplus](https://user-images.githubusercontent.com/31787822/78470460-c9346f80-774f-11ea-9066-aa1c4f0b6d26.png)

**Comment by huyphams** [comment]
Can you show me the data on the right sidebar @ZayRTun thank you!
<img width="1135" alt="abc" src="https://user-images.githubusercontent.com/3654622/78470543-92148d00-7754-11ea-8561-0302a75d320f.png">

**Comment by ZayRTun** [comment]
![tbp3](https://user-images.githubusercontent.com/31787822/78470747-a0ad7500-7751-11ea-9e9c-5e942ab61727.png)

**Comment by huyphams** [comment]
Thanks @ZayRTun please update to the build 48.

**Comment by ZayRTun** [comment]
Wow, it works now. Thanks, @huyphams. Really appreciated your prompt feedback.
