### ISSUE TITLE
Fails to launch on Ubuntu 19.10 (missing libmysqlclient.so.20)

### ISSUE THREAD

**Issue by PHLAK** [TablePlus/TablePlus-Linux#5]
1. Database version (Ex: PostgreSQL 10.0):

  - N/A

2. TablePlus version (the number on the welcome or about screen, Ex: build 81):

  - 0.1-7  

3. Linux distro (Ex: Ubuntu 18.04): 

  - Ubuntu 19.10

4. The steps to reproduce this issue:

  - Install on Ubuntu 19.10
  - Launch the app

When attempting to launch tableplus for the first time on Ubuntu 19.10 I saw the following:

```
tableplus: error while loading shared libraries: libgtksourceview-3.0.so.1: cannot open shared object file: No such file or directory
```

This was resolved by installing `libgtksourceview-3.0-1`. The next time I launched tableplus I got this error:

```
tableplus: error while loading shared libraries: libmysqlclient.so.20: cannot open shared object file: No such file or directory
```

Unfortunately Ubuntu 19.10 only has `libmysqlclient21` available via apt which includes `libmysqlclient.so.21` but not `libmysqlclient.so.20`.

**Comment by huyphams** [comment]
that's true, I'm working on it.

**Comment by huyphams** [comment]
Hi @PHLAK please run this command:
```
sudo apt update && sudo apt upgrade 
```
to update the client. Let me know if you're still seeing the issue.

**Comment by PHLAK** [comment]
Everything seems to be working now. Thank you.
