### ISSUE TITLE
"\" or "\\" not showing

### ISSUE THREAD

**Issue by Root3287** [TablePlus/TablePlus-Linux#50]
1. Database version (Ex: PostgreSQL 10.0):
MariaDB 10.3.22
2. TablePlus version (the number on the welcome or about screen, Ex: build 81):
Build 50
3. Linux distro (Ex: Ubuntu 18.04): 
Pop!_OS 19.10
4. The steps to reproduce this issue:

- Add a new row.
- Enter in a "\\" or "\\\\" in a field. 
- Commit.

Expected output:
Having a \\ or \\\\ in the database.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Thanks, I will fix it in next update!

**Comment by huyphams** [comment]
It's fixed in the newest release 52 thanks.
