### ISSUE TITLE
Tableplus quits when trying to open table with JSON columns

### ISSUE THREAD

**Issue by rogierverbrugge** [TablePlus/TablePlus-Linux#52]
1. Database version (Ex: PostgreSQL 10.0):
MySQL 5.7

2. TablePlus version (the number on the welcome or about screen, Ex: build 81):
0.1.50

3. Linux distro (Ex: Ubuntu 18.04): 
Mint @ 18.04.1-Ubuntu

4. The steps to reproduce this issue:
Open a table with JSON column structure.

**Comment by huyphams** [comment]
I just fixed it and pushed the update 52, please try it, thank you!

**Comment by rogierverbrugge** [comment]
Awesome! Works again :+1:
