### ISSUE TITLE
Impossible to close About Modal Window

### ISSUE THREAD

**Issue by rsyring** [TablePlus/TablePlus-Linux#55]
1. Database version (Ex: PostgreSQL 10.0):

 PostgreSQL 10+

2. TablePlus version (the number on the welcome or about screen, Ex: build 81):

0.1 (build 52)

3. Linux distro (Ex: Ubuntu 18.04): 

Ubuntu 19.10

4. The steps to reproduce this issue:

Open the About modal window:

![image](https://user-images.githubusercontent.com/109467/79694893-5e039680-8241-11ea-89ba-58ae4bdfc1c3.png)

Clicking Close does not close the window.  There is no way to close the window that I can find except to exit the program.  Additionally, if you click Credits, there is now way to make the credits go away to get back to the version info.

**Comment by dvkndn** [comment]
Sorry @rsyring .

This is weird.. we actually use the gtk's about dialog. As far as I know, most Gnome apps should also use this type of dialog. Have you ever experience this issue with other gtk apps, especially the Gnome ones?

In Ubuntu 18.04, I think Nautilus (Files), Calendar and Calculator may use the same dialog. Do they work fine for you?

**Comment by evansmwendwa** [comment]
Mine can close using the window title bar
![Screen Capture_select-area_20200420231852](https://user-images.githubusercontent.com/3830832/79795961-6cdf6b80-835d-11ea-8c93-76c541635a74.png)
 close button but the close button on the bottom isn't working

**Comment by huyphams** [comment]
Please let us know if you're still seeing this issue in build 74, thanks!
