### ISSUE TITLE
SQL Query not using monospace font

### ISSUE THREAD

**Issue by ecanuto** [TablePlus/TablePlus-Linux#57]
1. Database version (Ex: PostgreSQL 10.0):
Any

2. TablePlus version (the number on the welcome or about screen, Ex: build 81):
0.1.52

3. Linux distro (Ex: Ubuntu 18.04): 
Using Fedora

4. The steps to reproduce this issue:
Just open SQL Query tab and compare "W" with "1" or "a" and you can see different char have different sizes.

Maybe it is related to the fact I am using Fedora and TablePlus is using a monospaced font not installed on my system, the right behavior could be get system monospaced (fixed) font. An workaround could be tell us font used so we can try install it.

**Comment by huyphams** [comment]
It's fixed on the build 56.
