### ISSUE TITLE
Feature request: Allow adding colums to table

### ISSUE THREAD

**Issue by wout** [TablePlus/TablePlus-Linux#59]
1. Database version (Ex: PostgreSQL 10.0):
Any

2. TablePlus version (the number on the welcome or about screen, Ex: build 81):
0.1 (Build 54)

3. Linux distro (Ex: Ubuntu 18.04):
elementary OS 5.1.4

4. The steps to reproduce this issue:
N/A

Similar to the **`+ Row`** button, it would be great to have a **`+ Column`** in the Structure view. Currently, columns can be duplicated and edited, but not saved. On trying to save, the following error is thrown:

![image](https://user-images.githubusercontent.com/107324/81697825-375e0780-945d-11ea-9292-5b713fd20c15.png)

**Comment by huyphams** [comment]
We're working on this

**Comment by huyphams** [comment]
It's added in the build 74. Thanks
