### ISSUE TITLE
Linux Mint

### ISSUE THREAD

**Issue by f0ntana** [TablePlus/TablePlus-Linux#6]
When add on my linux mint
`sudo add-apt-repository "deb [arch=amd64] https://deb.tableplus.com/debian tableplus main"`
Malformed input, repository not added.

**Comment by f0ntana** [comment]
i resolved typing manually

**Comment by Ecuador-ManaWorld** [comment]
@f0ntana How did you resolve it? I'm facing the same issue.

**Comment by f0ntana** [comment]
> @f0ntana How did you resolve it? I'm facing the same issue.

# Add TablePlus gpg key
wget -O - -q http://deb.tableplus.com/apt.tableplus.com.gpg.key | sudo apt-key add - 

# Add TablePlus repo
sudo add-apt-repository "deb [arch=amd64] https://deb.tableplus.com/debian tableplus main"

# Install
sudo apt update
sudo apt install tableplus

**Comment by awalhadi** [comment]
My Linux mint Tableplus install process

# Add TablePlus gpg key
wget -qO - https://deb.tableplus.com/apt.tableplus.com.gpg.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/tableplus-archive.gpg > /dev/null

# Add TablePlus repo
sudo add-apt-repository "deb [arch=amd64] https://deb.tableplus.com/debian/24 tableplus main"

# Install
sudo apt update
sudo apt install tableplus

**Not open this app** after install. How to solve or I don't don't know what's going on. can you please anyone help me
