### ISSUE TITLE
MySQL, Tableplus build:54, Arch Linux. Cannot delete a row

### ISSUE THREAD

**Issue by orphikkkk** [TablePlus/TablePlus-Linux#64]
1. Database version (Ex: PostgreSQL 10.0):

2. TablePlus version (the number on the welcome or about screen, Ex: build 81):

3. Linux distro (Ex: Ubuntu 18.04): 

4. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by kevariable** [comment]
in my case,  I do not connect to database in Arch Linux
