### ISSUE TITLE
Aarch64 version

### ISSUE THREAD

**Issue by baarkerlounger** [TablePlus/TablePlus-Linux#69]
Any chance of a release that'll run on aarch64?

**Comment by huyphams** [comment]
You can try this repo @baarkerlounger https://aur.archlinux.org/packages/tableplus/

**Comment by baarkerlounger** [comment]
That looks like it's based on an `amd64.deb`?

**Comment by adojck** [comment]
I'm also interested in aarch64 (ARM64) version. Note that aarch64 is a CPU architecture, like x86_64/AMD64 as example. It is not an operating system, which was assumed by huyphams.

**Comment by huyphams** [comment]
I've built a `aarch64` version of TablePlus Linux but I'm not sure if I should publish it or not. Could you guys tell me more about your `aarch64` setup? Which devices are you using TablePlus Linux?

<img width="1154" alt="Screenshot 2023-03-01 at 10 24 40 PM" src="https://user-images.githubusercontent.com/3654622/222184759-8e493b42-17c0-407b-b4db-bebc28f8b2fa.png">

**Comment by baarkerlounger** [comment]
Pinebook Pro with debian

**Comment by huyphams** [comment]
You may want to try the build at:

```
# Add TablePlus gpg key
wget -qO - https://deb.tableplus.com/apt.tableplus.com.gpg.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/tableplus-archive.gpg > /dev/null

# Add TablePlus repo
sudo add-apt-repository "deb [arch=arm64] https://deb.tableplus.com/debian/22-arm tableplus main"

# Install
sudo apt update
sudo apt install tableplus
```

**Comment by huyphams** [comment]
Please also install those package if they are missing:
```
 sudo apt install libssh-dev libpq-dev
```

**Comment by baarkerlounger** [comment]
Works nicely. Thanks!
