### ISSUE TITLE
Tableplus keeps on connecting

### ISSUE THREAD

**Issue by ShreyasAmbre** [TablePlus/TablePlus-Linux#72]
1. CAssandra 4.0 (Ex: PostgreSQL 10.0):

2. TablePlus  0.1.60

3. Ubuntu 20 

4.Install Tableplus on ubuntu using docs
   -After opening Tableplus connection panel and ethering the required fiels such as host ip, port number, connection name and        selecting database.
   -after clicking connect button its keeps on connecting and it never get connected.

**Comment by mjahmadi** [comment]
same problem here :(

**Comment by huyphams** [comment]
The Cassandra requires dual SSH channels. TablePlus haven't supported it, so it will not work. We will support dual channels later.

**Comment by huyphams** [comment]
Hi @ShreyasAmbre @mjahmadi please upgrade to the build 140 it should fix this isuse.
