### ISSUE TITLE
Open Anything feature doesn't work.

### ISSUE THREAD

**Issue by Marlysson** [TablePlus/TablePlus-Linux#73]
2. TablePlus version (the number on the welcome or about screen, Ex: build 81):
0.1 (Build 60)

3. Linux distro (Ex: Ubuntu 18.04): 
Elementary OS 5.0 Juno

4. The steps to reproduce this issue:
- Connect with some postgres database and press shortcut: Ctrl + P. 
The search anything dont appear.

**Comment by Akkadius** [comment]
@huyphams trying to not open another issue here. I've given feedback around TablePlus in the past and you've been very helpful

I am now trying to get desktop parity in Linux today after using TablePlus (paid several licenses) for years now and one thing that is already painfully missing is the hotkeys

Command + P / Command + K searching is huge in my workflows, I fly around TablePlus exclusively using hotkeys and this hurts

Is there anyway I can help accelerate or bump getting support for this on Linux ?

<3

**Comment by huyphams** [comment]
It will be added in the next release!
Thanks
