### ISSUE TITLE
add licence registration support

### ISSUE THREAD

**Issue by 1player** [TablePlus/TablePlus-Linux#74]
I was an happy paying user of TablePlus under macOS, now I'm back on Linux and I would like to keep supporting the project, especially the Linux development work.

Even if you want to keep the Linux version free while it is in beta, please let paying users register in the app to support development.

**Comment by huyphams** [comment]
Thanks @1player for the suggestion, we're trying out best to release the stable version asap. Please let us know if you need any urgent features.
