### ISSUE TITLE
[Feature] Rebind Ctrl+S to "Preview Changes"

### ISSUE THREAD

**Issue by PHLAK** [TablePlus/TablePlus-Linux#78]
1. Database version: N/A
2. TablePlus version: Version 0.1 (64)
3. Linux distro:  Ubuntu 20.04.1
4. The steps to reproduce this issue: N/A

---

I would like the option to set <kbd>Ctrl</kbd>+<kbd>S</kbd> to the "Preview Changes" action instead of "Commit Changes" (immediately). This would prevent me from accidentally committing changes that I wanted to/should have previewed first.

**Comment by huyphams** [comment]
Hi @PHLAK we have implemented the safe mode. You can enable it so everytime you press command + S it will show you a nice warning popup!

**Comment by PHLAK** [comment]
Awesome! Thank you!
