### ISSUE TITLE
TablePlus is not working on ubuntu 16.04 

### ISSUE THREAD

**Issue by owiesnama** [TablePlus/TablePlus-Linux#79]
After installing Table Plus it's not working, I tried to run it from the terminal and it response with this message 
```
tableplus: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by tableplus)
``` 
OS: Ubuntu 16.04

**Comment by dvkndn** [comment]
While in the alpha we can't guarantee support for 16.04. However there are some workarounds already regarding this specific error. You can search in the repo or I'll find it later

**Comment by owiesnama** [comment]
@dvkndn Thanks for response, I checked #28 and it suggests rebuilding or switch to new version of GLIBC_2.25, I'll try to rebuild it .
