### ISSUE TITLE
Fails to launch on Manjaro (missing libmysqlclient.so.20)

### ISSUE THREAD

**Issue by credocoder** [TablePlus/TablePlus-Linux#8]
1. Database version: mariadb 15.1

2. TablePlus version: 0.1_12-1

3. Linux distro: Manjaro 18.1.3

4. The steps to reproduce this 

- install on manjaro

- Launch the app

When I run the program I get this error:
`tableplus: error while loading shared libraries: libmysqlclient.so.20: cannot open shared object file: No such file or directory`
and 
`tableplus: error while loading shared libraries: libgee.so: cannot open shared object file: No such file or directory`
What should I do?

**Comment by lmindwarel** [comment]
Hi, you need to manually install missing libraries with apt-get.
For exemple: 
`sudo apt-get install libmysqlclientXX libgeeXX`
XX is the version for your distro, you can use tabulation while typing to show available versions.

Good luck :)

**Comment by evansmwendwa** [comment]
From my system I can install `default-libmysqlclient-dev` but not `libmysqlclient-dev` which is the requested depndency

**Comment by lmindwarel** [comment]
Did you try to install `default-libmysqlclient-dev` ?. It can work.
For me I have `libmysqlclient20` installed and it work

**Comment by wastrachan** [comment]
@huyphams I did have to patch the `tableplus.desktop` shortcut in the Arch package to actually add the library you bundled to `LD_LIBRARY_PATH`. This might be applicable here as well. 

https://aur.archlinux.org/cgit/aur.git/tree/tableplus.desktop.patch?h=tableplus

**Comment by huyphams** [comment]
Hey, TablePlus Build 16 now statically links all database drivers! 🎉

**Comment by purejoy** [comment]
> Hey, TablePlus Build 16 now statically links all database drivers! 🎉

Why not build against a newer MySQL connector? The bundled libmysqlclient.so.20 depends on OpenSSL,however some of us has migrated to libreSSL.

**Comment by huyphams** [comment]
@purejoy I'm using Ubuntu 18.04 and it's the latest stable version of MySQL which is shipped with Ubuntu 18.04.
Sure, I will build the MySQL lib (and all others libs) with the latest release in the future updates.

**Comment by huyphams** [comment]
Btw, it's statically linked with libmysqlclient so it has nothing to do with OpenSSL or libreSSL in your environment, which was the error you have got @purejoy?

**Comment by purejoy** [comment]
I haven’t try the latest build but got an error said missing libssl.so.1.1 while running the 12th-build.

**Comment by huyphams** [comment]
Please try with the build 16, it resolves the issue!

**Comment by credocoder** [comment]
> Please try with the build 16, it resolves the issue!

Thank

**Comment by purejoy** [comment]
> Please try with the build 16, it resolves the issue!

Ok,thanks! I’ll will give it a try.
