### ISSUE TITLE
Database not selected automatically

### ISSUE THREAD

**Issue by azizramdan** [TablePlus/TablePlus-Linux#81]
1. Database version (Ex: PostgreSQL 10.0): 10.5.4-MariaDB-1:10.5.4+maria~focal

2. TablePlus version (the number on the welcome or about screen, Ex: build 81): build 64

3. Linux distro (Ex: Ubuntu 18.04): MX Linux 19.2

4. The steps to reproduce this issue: on connection configuration I set "database name" field, when I click connect, database that I set before not selected

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
It's fixed in the release 94 thanks!
