### ISSUE TITLE
Couldn't install from official repository

### ISSUE THREAD

**Issue by magwojtek** [TablePlus/TablePlus-Linux#83]
1. Database version (Ex: PostgreSQL 12.0):

2. Linux distro Ubuntu 20.04: 

3. The steps to reproduce this issue:

cannot install, apt couldn't find public key
https://deb.tableplus.com/debian tableplus InRelease   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 2A17818B38772786

**Comment by El-Nazy** [comment]
I'm having this same issue
