### ISSUE TITLE
Sorting data by ID (or any numeric field) sorts it alphabetically

### ISSUE THREAD

**Issue by chrisbjr** [TablePlus/TablePlus-Linux#9]
1. Database version: MySQL 8.0.18

2. TablePlus version: Build 12

3. Linux distro: POP OS 19.10 (ubuntu base)

4. The steps to reproduce this issue:

Go inside a table -> sort by ID:

![Screenshot 2019-12-04 00:17:44](https://user-images.githubusercontent.com/571279/70068751-8b9dc980-162b-11ea-917d-6bb543de7eb2.png)

It doesn't sort the data numerically but alphabetically, I think.

**Comment by huyphams** [comment]
It's fixed now.

**Comment by chrisbjr** [comment]
Not sure how to check, is there a new build?

**Comment by huyphams** [comment]
If you're using Ubuntu or Debian, you can update the app by run this command:
```
sudo apt update && sudo apt upgrade
```

**Comment by chrisbjr** [comment]
Confirmed fixed in build 20 :) Thanks @huyphams
