### ISSUE TITLE
UI Bug in Table Row (Ubuntu)

### ISSUE THREAD

**Issue by ptcampbell** [TablePlus/TablePlus-Linux#92]
![image](https://user-images.githubusercontent.com/876594/103437738-24f92f80-4be0-11eb-88f3-7ef6d8150871.png)

Table row styles are not rendering properly. See strings `EMPTY` and `rgb()` values. 

This is popOS / gnome. 

Thanks for making this great program.

**Comment by huyphams** [comment]
Hi @ptcampbell please don't remove the issue template questions

**Comment by huyphams** [comment]
Please download our latest release, it should be fixed now.
