### ISSUE TITLE
Error adding gpg key on PopOS 20.10

### ISSUE THREAD

**Issue by hoangtrann** [TablePlus/TablePlus-Linux#95]
1. Database version (Ex: PostgreSQL 10.0):

2. TablePlus version (the number on the welcome or about screen, Ex: build 81):

3. Linux distro (Ex: Ubuntu 18.04): 

Pop Os 20.10, might be on Ubuntu 20.10 or 20.04 as well

4. The steps to reproduce this issue:

Install Table Plus as installation guide on website, error is due to apt-get deprecation while add gpg key

```
wget -O- -q http://deb.tableplus.com/apt.tableplus.com.gpg.key | sudo apt-key add - 
```

To fix this, use the following command instead

```
wget -O- -q http://deb.tableplus.com/apt.tableplus.com.gpg.key | sudo gpg --dearmor -o /usr/share/keyrings/tableplus-archive-keyring.gpg

echo "deb [arch=amd64 signed-by=/usr/share/keyrings/tableplus-archive-keyring.gpg] https://deb.tableplus.com/debian tableplus main" | sudo tee /etc/apt/sources.list.d/tableplus.list > /dev/null
```

**Comment by huyphams** [comment]
I updated the instructions:
```
wget -qO - https://deb.tableplus.com/apt.tableplus.com.gpg.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/tableplus-archive.gpg
```
Thanks all.
