### ISSUE TITLE
Hundreds of pg_toast_temp_* and pg_temp_* are listed in the schema selection dropdown

### ISSUE THREAD

**Issue by somethvictory** [TablePlus/TablePlus-Linux#97]
1. Database version (PostgreSQL 10.12):

2. TablePlus version (build 74):

3. Linux distro (Ubuntu 20.04): 

4. The steps to reproduce this issue:

- Make a new connection to staging/production database over SSH Tunnel

![Image from iOS](https://user-images.githubusercontent.com/1940423/105793891-e7ac7580-5fc4-11eb-9fd7-047566c791f2.jpg)

Expectation:
- It should automatically filter out pg_* schema names
- Something like: `select * from pg_namespace where not nspname like 'pg_%';`

**Comment by somethvictory** [comment]
@huyphams @brysonreece any update?

**Comment by brysonreece** [comment]
Sorry for taking so long to get back to you; I'm not an active maintainer of this project. Tagging @huyphams for review.

**Comment by huyphams** [comment]
It should be fixed in the build 78, Thanks!
